(OTBALN)=

# 2.1 Operaciones y transformaciones básicas del Álgebra Lineal Numérica

```{admonition} Notas para contenedor de docker:

Comando de docker para ejecución de la nota de forma local:

nota: cambiar `<ruta a mi directorio>` por la ruta de directorio que se desea mapear a `/datos` dentro del contenedor de docker.

`docker run --rm -v <ruta a mi directorio>:/datos --name jupyterlab_optimizacion -p 8888:8888 -d palmoreck/jupyterlab_optimizacion:2.1.4`

password para jupyterlab: `qwerty`

Detener el contenedor de docker:

`docker stop jupyterlab_optimizacion`

Documentación de la imagen de docker `palmoreck/jupyterlab_optimizacion:2.1.4` en [liga](https://github.com/palmoreck/dockerfiles/tree/master/jupyterlab/optimizacion).

```

---

Nota generada a partir de [liga1](https://www.dropbox.com/s/fyqwiqasqaa3wlt/3.1.1.Multiplicacion_de_matrices_y_estructura_de_datos.pdf?dl=0), [liga2](https://www.dropbox.com/s/jwu8lu4r14pb7ut/3.2.1.Sistemas_de_ecuaciones_lineales_eliminacion_Gaussiana_y_factorizacion_LU.pdf?dl=0) y [liga3](https://www.dropbox.com/s/s4ch0ww1687pl76/3.2.2.Factorizaciones_matriciales_SVD_Cholesky_QR.pdf?dl=0).

Las operaciones básicas del Álgebra Lineal Numérica podemos dividirlas en vectoriales y matriciales.

## Vectoriales

* **Transponer:** $\mathbb{R}^{n \times 1}  \rightarrow \mathbb{R} ^{1 \times n}$: $y = x^T$ entonces

$$x = 
\left[
\begin{array}{c}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{array}
\right ]
$$
y se tiene:

$$ y = x^T = [x_1, x_2, \dots, x_n].$$

* **Suma:** $\mathbb{R}^n  \times \mathbb{R} ^n \rightarrow \mathbb{R}^n$: $z = x + y$ entonces $z_i = x_i + y_i$

* **Multiplicación por un escalar:** $\mathbb{R} \times \mathbb{R} ^n \rightarrow \mathbb{R}^n$: $y = \alpha x$ entonces $y_i = \alpha x_i$.

* **Producto interno estándar o producto punto:** $\mathbb{R}^n \times \mathbb{R} ^n \rightarrow \mathbb{R}$: $c = x^Ty$ entonces $c = \displaystyle \sum_{i=1}^n x_i y_i$.


* **Multiplicación *point wise:*** $\mathbb{R}^n \times \mathbb{R} ^n \rightarrow \mathbb{R}^n$: $z = x.*y$ entonces $z_i = x_i y_i$.

* **División *point wise:*** $\mathbb{R}^n \times \mathbb{R} ^n \rightarrow \mathbb{R}^n$: $z = x./y$ entonces $z_i = x_i /y_i$ con $y_i \neq 0$.


* **Producto exterior o *outer product*:** $\mathbb{R}^n \times \mathbb{R} ^n \rightarrow \mathbb{R}^{n \times n}$: $A = xy^T$ entonces $A[i, :] = x_i y^T$ con $A[i,:]$ el $i$-ésimo renglón de $A$.

## Matriciales


* **Transponer:** $\mathbb{R}^{m \times n} \rightarrow \mathbb{R}^{n \times m}$: $C = A^T$ entonces $c_{ij} = a_{ij}$.

* **Sumar:** $\mathbb{R}^{m \times n} \times \mathbb{R}^{m \times n} \rightarrow \mathbb{R}^{m \times n}$: $C = A + B$ entonces $c_{ij} = a_{ij} + b_{ij}$.

* **Multiplicación por un escalar:** $\mathbb{R} \times \mathbb{R}^{m \times n} \rightarrow \mathbb{R}^{m \times n}$: $C = \alpha A$ entonces $c_{ij} = \alpha a_{ij}$

* **Multiplicación por un vector:** $\mathbb{R}^{m \times n} \times \mathbb{R}^{n} \rightarrow \mathbb{R}^{m}$: $y = Ax$ entonces $y_i = \displaystyle \sum_{j=1}^n a_{ij}x_j$.

* **Multiplicación entre matrices:** $\mathbb{R}^{m \times k} \times \mathbb{R}^{k \times n} \rightarrow \mathbb{R}^{m \times n}$: $C = AB$ entonces $c_{ij} = \displaystyle \sum_{r=1}^k a_{ir}b_{rj}$.

* **Multiplicación *point wise*:** $\mathbb{R}^{m \times n} \times \mathbb{R}^{m \times n} \rightarrow \mathbb{R}^{m \times n}$: $C = A.*B$ entonces $c_{ij} = a_{ij}b_{ij}$.


* **División *point wise*:** $\mathbb{R}^{m \times n} \times \mathbb{R}^{m \times n} \rightarrow \mathbb{R}^{m \times n}$: $C = A./B$ entonces $c_{ij} = a_{ij}/b_{ij}$ con $b_{ij} \neq 0$.



**Como ejemplos de transformaciones básicas del Álgebra Lineal Numérica se encuentran:**

## Transformaciones de Gauss

In [1]:
import numpy as np

En esta sección suponemos que $A \in \mathbb{R}^{n \times n}$ y $A$ es una matriz con entradas $a_{ij} \in \mathbb{R}^{n \times n} \forall i,j=1,2,\dots,n$.

```{margin}

Como ejemplo de vector canónico tenemos: $e_1=(1,0)^T$ en $\mathbb{R}^2$ o $e_3 = (0,0,1,0,0)$ en $\mathbb{R}^5$.
```

Considérese al vector $a \in \mathbb{R}^{n}$ y $e_k \in \mathbb{R}^n$ el $k$-ésimo vector canónico: vector con un $1$ en la posición $k$ y ceros en las entradas restantes.

```{admonition} Definición

Una transformación de Gauss está definida de forma general como $L_k = I_n - \ell_ke_k^T$ con $\ell_k = (0,0,\dots,\ell_{k+1,k},\dots,\ell_{n,k})^T$ y $\ell_{i,k}=\frac{a_{ik}}{a_{kk}} \forall i=k+1,\dots,n$.
```

Las transformaciones de Gauss se utilizan para hacer ceros por debajo del **pivote**.

### Ejemplo aplicando transformaciones de Gauss a un vector

Considérese al vector $a=(-2,3,4)^T$. Definir una transformación de Gauss para hacer ceros por debajo de $a_1$ y otra transformación de Gauss para hacer cero la entrada $a_3$

**Solución:**

a)Para hacer ceros por debajo del **pivote** $a_1 = -2$:

In [2]:
a = np.array([-2,3,4])

In [3]:
pivote = a[0]

```{margin} 

Recuerda la definición de $l_1=(0, \frac{a_2}{a_1}, \frac{a_3}{a_1})^T$
```

In [4]:
l1 = np.array([0,a[1]/pivote, a[2]/pivote])

In [5]:
e1 = np.array([1,0,0])

```{margin}

Observa que por la definición de la transformación de Gauss, **no necesitamos construir a la matriz $L_1$, directamente se tiene $L_1a = a - \ell_1 e_1^Ta$.**
```

In [6]:
L1_a = a-l1*(e1.dot(a))

In [7]:
L1_a

array([-2.,  0.,  0.])

A continuación se muestra que el producto $L_1 a$ si se construye $L_1$ es equivalente a lo anterior:

```{margin}
$L_1 = I_3 - \ell_1 e_1^T$.
```

In [8]:
L1 = np.eye(3) - np.outer(l1,e1)

In [9]:
L1

array([[1. , 0. , 0. ],
       [1.5, 1. , 0. ],
       [2. , 0. , 1. ]])

In [10]:
L1@a

array([-2.,  0.,  0.])

b) Para hacer ceros por debajo del **pivote** $a_2 = 3$:

In [11]:
a = np.array([-2,3,4])

In [12]:
pivote = a[1]

```{margin} Recuerda
La definición de $l_2=(0, 0, \frac{a_3}{a_2})^T$
```

In [13]:
l2 = np.array([0,0, a[2]/pivote])

In [14]:
e2 = np.array([0,1,0])

```{margin}

Observa que por la definición de la transformación de Gauss, **no necesitamos construir a la matriz $L_2$, directamente se tiene $L_2a = a - \ell_2 e_2^Ta$.**
```

In [15]:
L2_a = a-l2*(e2.dot(a))

In [16]:
L2_a

array([-2.,  3.,  0.])

A continuación se muestra que el producto $L_2 a$ si se construye $L_2$ es equivalente a lo anterior:

```{margin}

$L_2 = I_3 - \ell_2 e_2^T$.
```

In [17]:
L2 = np.eye(3) - np.outer(l2,e2)

In [18]:
L2

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ],
       [ 0.        , -1.33333333,  1.        ]])

In [19]:
L2@a

array([-2.,  3.,  0.])

### Ejemplo aplicando transformaciones de Gauss a una matriz

Si tenemos una matriz $A \in \mathbb{R}^{3 \times 3}$ y queremos hacer ceros por debajo de su diagonal, realizamos los productos matriciales:

$$L_2 L_1 A$$

donde: $L_1, L_2$ son transformaciones de Gauss.

**Ejemplo:**

a) Utilizando $L_1$

In [20]:
A = np.array([[-1, 2, 5],
              [4, 5, -7],
              [3, 0, 8]])

In [21]:
A

array([[-1,  2,  5],
       [ 4,  5, -7],
       [ 3,  0,  8]])

Para hacer ceros por debajo del **pivote** $a_{11} = -1$:

In [22]:
pivote = A[0, 0]

```{margin} 

Recuerda la definición de $l_1=(0, \frac{a_{21}}{a_{11}}, \frac{a_{31}}{a_{11}})^T$
```

In [23]:
l1 = np.array([0,A[1,0]/pivote, A[2,0]/pivote])

In [24]:
e1 = np.array([1,0,0])

```{margin}

Observa que por la definición de la transformación de Gauss, **no necesitamos construir a la matriz $L_1$, directamente se tiene $L_1 A[:,1] = A[:,1] - \ell_1 e_1^T A[:,1]$.**
```

In [25]:
L1_A_1 = A[:,0]-l1*(e1.dot(A[:,0]))

In [26]:
L1_A_1

array([-1.,  0.,  0.])

**Y se debe aplicar $\ell_1$ a las columnas número 2 y 3 de $A$ para completar el producto $L_1A$:**

```{margin}

Aplicando $L_1$ a la segunda columna de $A$: $A[:,2]$.

```

In [27]:
L1_A_2 = A[:,1]-l1*(e1.dot(A[:,1]))

In [28]:
L1_A_2

array([ 2., 13.,  6.])

```{margin}

Aplicando $L_1$ a la tercer columna de $A$: $A[:,3]$.

```

In [29]:
L1_A_3 = A[:,2]-l1*(e1.dot(A[:,2]))

In [30]:
L1_A_3

array([ 5., 13., 23.])

A continuación se muestra que el producto $L_1 A$ si se construye $L_1$ es equivalente a lo anterior:

```{margin}
$L_1 = I_3 - \ell_1 e_1^T$.
```

In [31]:
L1 = np.eye(3) - np.outer(l1,e1)

In [32]:
L1

array([[1., 0., 0.],
       [4., 1., 0.],
       [3., 0., 1.]])

In [33]:
L1 @ A

array([[-1.,  2.,  5.],
       [ 0., 13., 13.],
       [ 0.,  6., 23.]])

```{admonition} Observación
:class: tip

Al aplicar $\ell_1$ a la primer columna de $A$ **siempre** obtenemos ceros por debajo del pivote que en este caso es $a_{11}$.
```

**Después de hacer la multiplicación $L_1A$ en cualquiera de los dos casos (construyendo o no explícitamente $L_1$) no se modifica el primer renglón de $A$:**


In [34]:
A

array([[-1,  2,  5],
       [ 4,  5, -7],
       [ 3,  0,  8]])

```{margin}

Este es el primer renglón de $A$.

```

In [35]:
A[0,:]

array([-1,  2,  5])

```{margin}

Tomando el primer renglón del producto $L_1A$.
```

In [36]:
(L1 @ A)[0,:]

array([-1.,  2.,  5.])

**por lo que la multiplicación $L_1A$ entonces modifica del segundo renglón de $A$ en adelante y de la segunda columna de $A$ en adelante.**


```{admonition} Observación
:class: tip

Dada la forma de $L_1 = I_n - \ell_1e_1^T$, al hacer la multiplicación por la segunda y tercer columna de $A$ se tiene:

$$e_1^T A[:,2] = A[0,2]$$

$$e_1^T A[:,3] = A[0,3]$$

respectivamente.
```

```{margin}

El resultado de este producto es un escalar.
```

In [37]:
e1.dot(A[:, 1])

2

```{margin}

El resultado de este producto es un escalar.
```

In [38]:
e1.dot(A[:, 2])

5

y puede escribirse de forma compacta:

$$e_1^T A[:,2:3] = A[0, 2:3]$$

In [39]:
A[0, 1:3] #observe that we have to use 2+1=3 as the second number after ":" in 1:3

array([2, 5])

In [40]:
A[0, 1:] #also we could have use this statement

array([2, 5])

Entonces los productos $\ell_1 e_1^T A[:,2]$ y $\ell_1 e_1^T A[:,3]$ quedan respectivamente como:

$$\ell_1A[0, 2]$$

In [41]:
l1*A[0,1]

array([ 0., -8., -6.])

$$\ell_1A[0,3]$$

In [42]:
l1*A[0, 2]

array([  0., -20., -15.])

```{admonition} Observación
:class: tip

En los dos cálculos anteriores, las primeras entradas son iguales a $0$ por lo que es consistente con el hecho que únicamente se modifican dos entradas de la segunda y tercer columna de $A$.
```

De forma compacta y aprovechando funciones en `numpy` como `outer` se puede calcular lo anterior como:

In [43]:
np.outer(l1[1:3],A[0,1:3])

array([[ -8., -20.],
       [ -6., -15.]])

In [44]:
np.outer(l1[1:],A[0,1:]) #also we could have use this statement

array([[ -8., -20.],
       [ -6., -15.]])

Y finalmente la aplicación de $L_1$ al segundo renglón y segunda columna en adelante de $A$ queda:

```{margin}

Observa que por la definición de la transformación de Gauss, **no necesitamos construir a la matriz $L_1$, directamente se tiene $L_1 A = A - \ell_1 e_1^T A$ y podemos aprovechar lo anterior para sólo operar de la segunda columna y segundo renglón en adelante.**
```

In [45]:
A[1:, 1:] - np.outer(l1[1:],A[0,1:])

array([[13., 13.],
       [ 6., 23.]])

Compárese con:

In [51]:
L1 @ A

array([[-1.,  2.,  5.],
       [ 0., 13., 13.],
       [ 0.,  6., 23.]])

Entonces sólo falta colocar el primer renglón y primera columna al producto. Para esto combinamos columnas y renglones en *numpy* con [column_stack](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html) y *row_stack*:

In [46]:
A_aux = A[1:, 1:] - np.outer(l1[1:],A[0,1:])

In [47]:
m, n = A.shape
number_of_zeros = m-1
A_aux_2 = np.column_stack((np.zeros(number_of_zeros), A_aux)) # stack two zeros

In [48]:
A_aux_2

array([[ 0., 13., 13.],
       [ 0.,  6., 23.]])

In [49]:
A_aux_3 = np.row_stack((A[0, :], A_aux_2))

In [50]:
A_aux_3

array([[-1.,  2.,  5.],
       [ 0., 13., 13.],
       [ 0.,  6., 23.]])

que es el resultado de:

In [51]:
L1 @ A

array([[-1.,  2.,  5.],
       [ 0., 13., 13.],
       [ 0.,  6., 23.]])

```{admonition} Ejercicio
:class: tip

Calcular el producto $L_2 L_1 A$ para la matriz anterior y para la matriz:

$$
A = \left [
\begin{array}{ccc}
1 & 4 & -2 \\
-3 & 9 & 8 \\
5 & 1 & -6
\end{array}
\right]
$$
```

```{admonition} Comentario

Las transformaciones de Gauss se utilizan para la fase de eliminación del método de eliminación Gaussiana o también llamada factorización LU. Ver [Gaussian elimination](https://en.wikipedia.org/wiki/Gaussian_elimination).
```

## Transformaciones de reflexión

### Matriz ortogonal y matriz con columnas ortonormales

Un conjunto de vectores $\{x_1, \dots, x_p\}$ en $\mathbb{R}^m$ ($x_i \in \mathbb{R}^m$)es ortogonal si $x_i^Tx_j=0$ $\forall i\neq j$. Por ejemplo, para un conjunto de $2$ vectores $x_1,x_2$ en $\mathbb{R}^3$ esto se visualiza:

<img src="https://dl.dropboxusercontent.com/s/cekagqnxe0grvu4/vectores_ortogonales.png?dl=0" heigth="550" width="550">


```{admonition} Comentarios

* Si el conjunto $\{x_1,\dots,x_p\}$ en $\mathbb{R}^m$ satisface $x_i^Tx_j= \delta_{ij}= \begin{cases}
1 &\text{ si } i=j,\\
0 &\text{ si } i\neq j
\end{cases}$ se le nombra conjunto **ortonormal**, esto es, constituye un conjunto ortogonal y cada elemento del conjunto tiene norma Euclidiana igual a $1$: $||x_i||_2 = 1, \forall i=1,\dots,p$.

* Si definimos a la matriz $X$ con columnas dadas por cada uno de los vectores del conjunto $\{x_1,\dots, x_p\}$: $X=(x_1, \dots , x_p) \in \mathbb{R}^{m \times p}$ entonces la propiedad de que cada par de columnas satisfaga $x_i^Tx_j=\delta_{ij}$ se puede escribir en notación matricial como $X^TX = I_p$ con $I_p$ la matriz identidad de tamaño $p$ o bien $XX^T=I_m$. A la matriz $X$ se le nombra **matriz con columnas ortonormales**.

* Si cada $x_i$ está en $\mathbb{R}^p$ (en lugar de $\mathbb{R}^m$) entonces construímos a la matriz $X$ como el punto anterior con la diferencia que $X \in \mathbb{R}^{p \times p}$. En este caso $X$ se le nombra **matriz ortogonal**.
```

### Reflectores de Householder

```{margin}

$span\{v\}$ es el conjunto generado por $v$. Se define como el conjunto de combinaciones lineales de $v$: $span\{v\} = \left \{\displaystyle \sum_{i=1}^m k_i v_i | k_i \in \mathbb{R} \forall i =1,\dots,m \right \}$. 
```

Las reflexiones de Householder son **matrices** simétricas, ortogonales y se construyen a partir de un vector $v \neq 0$ definiendo:

$$R = I_m-\beta v v^T$$ 

con $v \in \mathbb{R}^m - \{0\}$ y $\beta = \frac{2}{v^Tv}$. El vector $v$ se llama **vector de Householder**. La multiplicación $Rx$ representa la reflexión del vector $x \in \mathbb{R}^m$ a través del hiperplano $span\{v\}^\perp$.


Algunas propiedades de las reflexiones de Householder son: $R^TR = R^2 = I_m$, $R^{-1}=R$, $det(R)=-1$.


```{sidebar} Proyector ortogonal elemental

En este dibujo se utiliza el **proyector ortogonal elemental** sobre el complemento ortogonal de u: $u^\perp = \{x \in \mathbb{R}^m| u^Tx=0\}$ (que es un subespacio de $\mathbb{R}^m$ de dimensión $m-1$) definido como: $P=I_m- u u^T$ y $Px$ es la proyección ortogonal de $x$ sobre $u^\perp$ . Los proyectores ortogonales elementales **no** son matrices ortogonales, son singulares, son simétricas y $P^2=P$. El proyector ortogonal elemental de $x$ sobre $u^\perp$ tienen $rank$ igual a $m-1$ y el proyector ortogonal de $x$ sobre $span\{u\}$ definido por $I_m-P=uu^T$ tienen $rank$ igual a $1$.

<img src="https://dl.dropboxusercontent.com/s/itjn9edajx4g2ql/elementary_projector_drawing.png?dl=0" heigth="350" width="350">
```

Un dibujo que representa lo anterior es el siguiente en el que se utiliza $u \in \mathbb{R}^m - \{0\}$ , $||u||_2 = 1$ y  $R=I_m-2 u u^T$, el reflector elemental alrededor de $u^\perp$:

<img src="https://dl.dropboxusercontent.com/s/o3oht181nm8lfit/householder_drawing.png?dl=0" heigth="350" width="350">



Las reflexiones de Householder pueden utilizarse para hacer ceros por debajo de una entrada de un vector. Por ejemplo:

In [2]:
x = np.array([1,2,3])

In [3]:
x

array([1, 2, 3])

Utilizamos la definición $v=x-||x||_2e_1$ con $e_1=(1,0,0)^T$ vector canónico para construir al vector de Householder:

In [4]:
v = x-np.linalg.norm(x)*np.array([1,0,0]) #uno en la primer entrada pues se desea
                                          #hacer ceros en las entradas restantes

In [5]:
beta = 2/v.dot(v)


Hacemos ceros por debajo de la primera entrada de $x$ haciendo la multiplicación matriz-vector $Rx$. Pero para aplicar $Rx$ **no** construímos $R = I_3 -\beta vv^T$, en lugar de eso hacemos $Rx = x - \beta v v^Tx$:

In [6]:
x-beta*v*(v.dot(x))

array([3.74165739, 0.        , 0.        ])

obsérvese que el resultado de $Rx$ es $(||x||_2,0,0)^T$:

In [14]:
np.linalg.norm(x)

3.7416573867739413

Sólo para mostrar que $Rx$ construyendo $R$ es equivalente a lo anterior, se construye a continuación $R$:

In [17]:
R = np.eye(3)-beta*np.outer(v,np.transpose(v))

In [18]:
R

array([[ 0.26726124,  0.53452248,  0.80178373],
       [ 0.53452248,  0.61007346, -0.5848898 ],
       [ 0.80178373, -0.5848898 ,  0.12266529]])

In [19]:
R@x

array([3.74165739e+00, 0.00000000e+00, 2.22044605e-16])

**Otra opción para definir al vector de Householder es $v=x+||x||_2e_1$ con $e_1=(1,0,0)^T:$**


In [22]:
v = x+np.linalg.norm(x)*np.array([1,0,0]) #uno en la primer entrada pues se desea
                                          #hacer ceros en las entradas restantes

In [24]:
beta = 2/v.dot(v)

In [25]:
x-beta*v*(v.dot(x))

array([-3.74165739e+00, -4.44089210e-16, -4.44089210e-16])

**¿Cuál definición del vector de Householder usar?**

La respuesta a la pregunta tiene que ver con que en cualquiera de las dos definiciones del vector de Householder $v=x \pm ||x||_2 e_1$, la multiplicación $Rx$ refleja $x$ en el primer eje coordenado:


<img src="https://dl.dropboxusercontent.com/s/bfk7gojxm93ah5s/householder_2_posibilites.png?dl=0" heigth="400" width="400">


El vector $v^+ = - u_0^+ = x-||x||_2e_1$ refleja $x$ respecto al subespacio $H^+$. El vector $v^- = -u_0^- = x+||x||_2e_1$ refleja $x$ respecto al subespacio $H^-$. Para disminuir los errores por redondeo y evitar el problema de cancelación en la aritmética de punto flotante (ver [Sistema de punto flotante](https://itam-ds.github.io/analisis-numerico-computo-cientifico/I.computo_cientifico/1.2/Sistema_de_punto_flotante.html)) se utiliza $v = x+signo(x_1)||x||_2e_1$ donde $signo(x_1) = \begin{cases}
1 &\text{ si } x_1 \geq 0 ,\\
-1 &\text{ si } x_1 < 0
\end{cases}$. La idea de la definción anterior con la función $signo(\cdot)$ es que la reflexión (en el dibujo anterior $-||x||_2e_1$ o $||x||_2e_1$) sea lo más alejada posible de $x$. En el dibujo anterior como $x_1, x_2>0$ entonces se refleja respecto al subespacio $H^-$ quedando su reflexión igual a $-||x||_2e_1$.

```{admonition} Comentarios

* Otra forma de lidiar con el problema de cancelación es definiendo a la primera componente del vector de Householder $v_1$ como $v_1=x_1-||x||_2$ y haciendo una manipulación algebraica como sigue:

$$v_1=x_1-||x||_2 = \frac{x_1^2-||x||_2^2}{x_1+||x||_2} = -\frac{x_2^2+x_3^2+\dots + x_m^2}{x_1+||x||_2}.$$

* En la implementación del cálculo del vector de Householder, es útil que $v_1=1$ y así únicamente se almacenará $v(2:m)$. Al vector $v(2:m)$ se le nombra **parte esencial del vector de Householder**.

```

## Transformaciones de rotación

**Referencias:**

*  G. H. Golub, C. F. Van Loan, Matrix Computations, John Hopkins University Press, 2013.
