Nota generada a partir de [liga](https://www.dropbox.com/s/5bc6tn39o0qqg35/1.3.Condicion_estabilidad_y_normas.pdf?dl=0)

Comando de docker para ejecución de la nota de forma local:

nota: cambiar `<ruta a mi directorio>` por la ruta de directorio que se desea mapear a `/datos` dentro del contenedor de docker.

```
docker run --rm -v <ruta a mi directorio>:/datos --name jupyterlab-local -p 8888:8888 -d palmoreck/jupyterlab:1.1.0
```

Detener el contenedor de docker:

```
docker stop jupyterlab-local
```


In [ ]:
%pip install --user numpy

In [1]:
from IPython.core.display import HTML
HTML("<script>Jupyter.notebook.kernel.restart()</script>")

# 1.3 Condición de un problema y estabilidad de un algoritmo

Dos temas fundamentales en el análisis numérico son: la **condición de un problema** y **estabilidad de un algoritmo**. El condicionamiento tiene que ver con el comportamiento de un problema ante perturbaciones y la estabilidad con el comportamiento de un algoritmo (usado para resolver un problema) ante perturbaciones.

La exactitud de un cálculo dependerá finalmente de una combinación de estos términos:

<p style="text-align: center;">Exactitud = Condición + Estabilidad</p>

La falta de exactitud en un problema se presenta entonces por problemas mal condicionados (no importando si los algoritmos son estables o inestables) y algoritmos inestables (no importando si los problemas son mal o bien condicionados).

## Perturbaciones

La condición de un problema y estabilidad de un algoritmo hacen referencia al término **perturbación**. Tal término conduce a pensar en perturbaciones "chicas" o "grandes". Para dar una medida de lo anterior se utiliza el concepto de **norma**. Ver final de esta nota para definición de norma y propiedades.

## Condición de un problema

Pensemos a un problema como una función $f: \mathbb{X} \rightarrow \mathbb{Y}$ donde $\mathbb{X}$ es un espacio vectorial con norma definida y $\mathbb{Y}$ es otro espacio vectorial de soluciones con una norma definida. Llamemos instancia de un problema a la combinación entre $x,f$ y nos interesa el comportamiento de $f$ en $x$. Usamos el nombre de "problema" para referirnos al de instancia del problema.

Un problema (instancia) bien condicionado tiene la propiedad de que todas las perturbaciones pequeñas en $x$ conducen a pequeños cambios en $f(x)$. Y es mal condicionado si perturbaciones pequeñas en $x$ conducen a grandes cambios en $f(x)$. El uso de los términos "pequeño" o "grande" dependen del problema mismo.

Sea $\hat{x} = x + \Delta x$ con $\Delta x$ una perturbación pequeña de $x$.

El **número de condición relativo del problema $f$ en $x$** es:

$$\text{Cond}_f^R = \frac{\text{ErrRel}(f(\hat{x}))}{\text{ErrRel}(\hat{x})}  = \frac{\frac{||f(\hat{x})-f(x)||}{||f(x)||}}{\frac{||x-\hat{x}||}{||x||}}$$

considerando $x,f(x) \neq 0$.

**Obs:** si $f$ es una función diferenciable, podemos evaluar $\text{Cond}_f^R$ con la derivada de $f$, pues a primer orden (usando teorema de Taylor): $f(\hat{x})-f(x) \approx \mathcal{J}_f(x)\Delta x$ con igualdad para $\Delta x \rightarrow 0$ y $\mathcal{J}_f$ la Jacobiana de $f$ definida como una matriz con entradas: $(\mathcal{J}_f(x))_{ij} = \frac{\partial f_i(x)}{\partial x_j}$. Por tanto, se tiene:

$$\text{Cond}_{f}^R = \frac{||\mathcal{J}_f(x)||||x||}{||f(x)||}$$

y $||\mathcal{J}_f(x)||$ es una norma matricial inducida por las normas en $\mathbb{X}, \mathbb{Y}$. Ver final de esta nota para definición de norma y propiedades.

**Comentario:** en la práctica se considera a un problema **bien condicionado** si $\text{Cond}_f^R$ es "pequeño": de orden menor a  $10^1$, **medianamente bien condicionado** si es de orden entre $10^1$ y $10^2$ y **mal condicionado** si es "grande": mayor a $10^3$.

**Ejercicio:**

Calcular $\text{Cond}_f^R$ de los siguientes problemas. Para $x \in \mathbb{R}$ usa el valor absoluto y para $x \in \mathbb{R}^n$ usa $||x||_\infty$.

1. $x \in \mathbb{R} - \{0\}$. Problema: realizar la operación $\frac{x}{2}$.

2. $x \geq 0$. Problema: calcular $\sqrt{x}$.

3. $x \approx \frac{\pi}{2}$. Problema: calcular $\cos(x)$.

4. $x \in \mathbb{R}^2$. Problema: calcular $x_1-x_2$.

**Comentario:** las dificultades que pueden surgir al resolver un problema **no** siempre están relacionadas con una fórmula o un algoritmo mal diseñado sino con el problema en cuestión. En el ejercicio anterior, observamos que áun utilizando **aritmética exacta**, la solución del problema puede ser altamente sensible a perturbaciones a los datos de entrada. Por esto el número de condición relativo se define de acuerdo a perturbaciones en los datos de entrada y mide la perturbación en los datos de salida que uno espera: 

$$\text{Cond}_f^R = \frac{||\text{Cambios relativos en la solución}||}{||\text{Cambios relativos en los datos de entrada}||}.$$

## Estabilidad de un algoritmo

Pensemos a un algoritmo $\hat{f}$ como una función $\hat{f}:\mathbb{X}\rightarrow \mathbb{Y}$ para resolver el problema $f$ con datos $x \in \mathbb{X}$, donde $\mathbb{X}$ es un espacio vectorial con norma definida y $\mathbb{Y}$ es otro espacio vectorial con una norma definida.


La implantación del algoritmo $\hat{f}$ en una máquina conduce a considerar:

* Errores por redondeo:

$$fl(u) = u(1+\epsilon), |\epsilon| \leq \epsilon_{maq}, \forall u \in \mathbb{R}.$$

* Operaciones en un SPFN, $\mathcal{Fl}$. Por ejemplo para la suma:

$$u \oplus v  = fl(u+v) = (u + v)(1+\epsilon), |\epsilon|\leq \epsilon_{maq} \forall u,v \in \mathcal{Fl}.$$

Esto es, $\hat{f}$ depende de $x \in \mathbb{X}$ y $\epsilon_{maq}$: representación de los números reales en una máquina y operaciones entre ellos o aritmética de máquina. Ver nota: [1.2.Sistema_de_punto_flotante](https://github.com/ITAM-DS/analisis-numerico-computo-cientifico/blob/master/temas/I.computo_cientifico/1.2.Sistema_de_punto_flotante.ipynb).

Al ejecutar $\hat{f}$ obtenemos una colección de números en el SPFN que pertenecen a $\mathbb{Y}$: $\hat{f}(x)$.

Debido a las diferencias entre un problema con cantidades continuas y una máquina que trabaja con cantidades discretas, los algoritmos numéricos **no** son exactos para **cualquier** elección de datos $x \in \mathbb{X}$. Esto es, los algoritmos **no** cumplen que la cantidad: 

$$\frac{||\hat{f}(x)-f(x)||}{||f(x)||}$$

dependa únicamente de errores por redondeo al evaluar $f$ $\forall x \in \mathbb{X}$. En notación matemática:

$$\frac{||\hat{f}(x)-f(x)||}{||f(x)||} \leq K \epsilon_{maq} \forall x \in \mathbb{X}$$

con $K > 0$ no se cumple en general.

La razón de lo anterior tiene que ver con cuestiones en la implantación de $\hat{f}$ como el número de iteraciones, la representación de $x$ en un SPFN o el mal condicionamiento de $f$. Así, a los algoritmos en el análisis numérico, se les pide una condición menos estricta que la anterior y más bien satisfagan lo que se conoce como **estabilidad**. Se dice que un algoritmo $\hat{f}$ para un problema $f$ es **estable** si:

$$\forall x \in \mathbb{X}, \frac{||\hat{f}(x)-f(\hat{x})||}{||f(\hat{x})||} \leq K_1\epsilon_{maq}, K_1>0$$

para $\hat{x} \in \mathbb{X}$ tal que $\frac{||x-\hat{x}||}{||x||} \leq K_2\epsilon_{maq}, K_2>0$.

Esto es, $\hat{f}$ resuelve un problema cercano para datos cercanos (cercano en el sentido del $\epsilon_{maq}$) independientemente de la elección de $x$.

**Obs:** obsérvese que esta condición es más flexible y en general $K_1, K_2$ dependen de las dimensiones de $\mathbb{X},\mathbb{Y}$.

**Comentarios:**

* Esta definición resulta apropiada para la mayoría de los problemas en el ánalisis numérico. Para otras áreas, por ejemplo en ecuaciones diferenciales, donde se tienen definiciones de sistemas dinámicos estables e inestables (cuyas definiciones no se deben confundir con las descritas para algoritmos), esta condición es muy estricta.

* Tenemos algoritmos que satisfacen una condición más estricta y simple que la estabilidad: **estabilidad hacia atrás**:



### Estabilidad hacia atrás

Decimos que un algoritmo $\hat{f}$ para el problema $f$ es **estable hacia atrás** si:

$$\forall x \in \mathbb{X}, \hat{f}(x) = f(\hat{x})$$

con $\hat{x} \in \mathbb{X}$ tal que $\frac{||x-\hat{x}||}{||x||} \leq K\epsilon_{maq}, K>0$.

Esto es, el algoritmo $\hat{f}$ da la solución **exacta** para datos cercanos (cercano en el sentido de $\epsilon_{maq}$), independientemente de la elección de $x$.

**Comentario:** Para entender la estabilidad hacia atrás de un algoritmo, considérese el ejemplo siguiente. 

**Problema:** evaluar $f(x) = e^x$ en $x=1$.

**Resultado:** $f(1) = e^1 = 2.718281...$.



In [2]:
import math
x=1
math.exp(x)

2.718281828459045

**Algoritmo:** truncar la serie $1 + x + \frac{x^2}{2} + \frac{x^3}{6} + \dots $ a cuatro términos: $\hat{f}(x) = 1 + x + \frac{x^2}{2} + \frac{x^3}{6}$.

**Resultado del algoritmo:** $\hat{f}(1) = 2.\bar{6}$

In [3]:
algoritmo = lambda x: 1 + x + x**2/2.0 + x**3/6.0

In [4]:
algoritmo(1)

2.6666666666666665

**Pregunta:** ¿Qué valor $\hat{x} \in \mathbb{R}$ hace que el valor calculado por el algoritmo $\hat{f}(1)$ sea igual a $f(\hat{x})$?

-> **Solución:** 

Resolver la ecuación: $e^{\hat{x}} = 2.\bar{6}$, esto es: $\hat{x} = log(2.\bar{6}) = 0.980829...$. Entonces $f(\hat{x}) = 2.\bar{6} = \hat{f}(x)$.

In [5]:
x_hat = math.log(algoritmo(1))
x_hat

0.9808292530117262

Entonces, el algoritmo es estable hacia atrás sólo si la diferencia entre $x$ y $\hat{x}$ en términos relativos es menor a $K \epsilon_{maq}$ con $K >0$. Además, podemos calcular **errores hacia delante** y **errores hacia atrás**:

error hacia delante: $\hat{f}(x) - f(x) = -0.05161...$, error hacia atrás: $\hat{x}-x = -0.01917...$.

In [6]:
err_delante = algoritmo(x) - math.exp(x)
err_delante

-0.05161516179237857

In [7]:
err_atras = x_hat-x
err_atras

-0.019170746988273812

Dependiendo del problema estos errores son pequeños o grandes, por ejemplo si consideramos tener una cifra correcta como suficiente para determinar que es una buena aproximación entonces podemos concluir: $\hat{f}$ obtiene una respuesta correcta y cercana al valor de $f$ (error hacia delante) y la respuesta que obtuvimos con $\hat{f}$ es correcta para datos ligeramente perturbados (error hacia atrás).

**Obs:** 

1. Obsérvese que el error hacia delante requiere resolver el problema $f$ (para calcular $f(x)$) y de información sobre $f$.

2. En el ejemplo anterior se calculó $\hat{f}(x)$ y se calculó qué tan larga debe ser la modificación en los datos $x$, esto es: $\hat{x}$, para que $\hat{f}(x) = f(\hat{x})$ (error hacia atrás).

3. 

<p align="centered">
<img src="https://drive.google.com/uc?export=view&id=1O8JxFe1E2ttCH9nIJVeuatOZ_4y8WkUi" alt="a" heigth="500" width="500">
</p>



# 1.3.1 Número de condición de una matriz

En el curso trabajaremos con algoritmos matriciales que son numéricamente estables (o estables hacia atrás) ante errores por redondeo, sin embargo la exactitud que obtengamos con tales algoritmos dependerán de qué tan bien (o mal) condicionado esté el problema. En el caso de matrices la condición de un problema puede ser cuantificada con el **número de condición** de la matriz del problema. Aunque haciendo uso de definiciones como la pseudoinversa de una matriz es posible definir el número de condición para una matriz en general rectangular $A \in \mathbb{R}^{m\times n}$, en esta primera definición consideramos matrices cuadradas no singulares $A \in \mathbb{R}^{n\times n}$:

$$\text{cond}(A) = ||A|| ||A^{-1}||.$$

**Obs:** obsérvese que la norma anterior es una **norma matricial** y cond$(\cdot)$ puede calcularse para diferentes normas matriciales. Ver final de esta nota para definición de norma y propiedades.

## Preguntas:

### 1. ¿Por qué se utiliza la expresión $||A|| ||A^{-1}||$ para definir el número de condición de una matriz?

### 2. ¿Qué está midiendo el número de condición de una matriz respecto a un sistema de ecuaciones lineales?

**Para responder la primer pregunta...**

La primer pregunta tiene que ver con el hecho que tal expresión aparece frecuentemente en problemas típicos de matrices. Para lo anterior considérese los siguientes problemas $f$:

1.Sean $A \in \mathbb{R}^{n\times n}$ no singular, $x \in \mathbb{R}^n$ y $f$ el problema de realizar la multiplicación $Ax$ para $x$ fijo, esto es: $f: \mathbb{R}^n \rightarrow \mathbb{R}^n$ dada por $f(x) = Ax$. Considérese una perturbación en $x: \hat{x} = x + \Delta x$, entonces:

$$\text{Cond}_f^R = \frac{\text{ErrRel}(f(\hat{x}))}{\text{ErrRel}(\hat{x})} = \frac{\frac{||f(\hat{x})-f(x)||}{||f(x)||}}{\frac{||x-\hat{x}||}{||x||}} \approx \frac{||\mathcal{J}_f(x)||||x||}{||f(x)||}.$$

Para este problema tenemos: 

$$\frac{||\mathcal{J}_f(x)||||x||}{||f(x)||} = \frac{||A|| ||x||}{||Ax||}.$$

Si las normas matriciales utilizadas en el número de condición son consistentes (ver final de esta nota para definición de norma y propiedades) entonces: 

$$||x|| = ||A^{-1}Ax|| \leq ||A^{-1}||||Ax|| \therefore \frac{||x||}{||Ax||} \leq ||A^{-1}||$$

y se tiene:

$$\text{Cond}_f^R \leq ||A|| ||A^{-1}||.$$

2.Sean $f: \mathbb{R}^n \rightarrow \mathbb{R}, A \in \mathbb{R}^{n\times n}$ no singular. Considérese el problema de calcular $f(b) = A^{-1}b$ para $b \in \mathbb{R}^n$ fijo y la perturbación $\hat{b} = b + \Delta b$ entonces bajo las suposiciones del ejemplo anterior:

$$\text{Cond}_f^R \approx \frac{||A^{-1}|| ||b||}{||A^{-1}b||}.$$

Si las normas matriciales utilizadas en el número de condición son consistentes (ver final de esta nota para definición de norma y propiedades) entonces: 

$$||b|| = ||AA^{-1}b|| \leq ||A|| ||A^{-1}b|| \therefore \text{Cond}_f^R \leq ||A^{-1}|| ||A||.$$

3.Sean $f: \mathbb{R}^{n\times n} \rightarrow \mathbb{R}^n, A \in \mathbb{R}^{n\times n}$ no singular $b \in \mathbb{R}^n$ fijo. Considérese el problema de calcular la solución $x$ del sistema $Az=b$, esto es, calcular: $x = f(A) = A^{-1}b.$ Además, considérese la perturbación $\hat{A} = A + \Delta A$ en tal sistema $Az = b$. Se tiene:


$$\hat{x} = \hat{A}^{-1}b,$$

donde: $\hat{x} = x + \Delta x$ (si se perturba $A$ entonces se perturba también $x$).


De la ecuación anterior como $\hat{x} = \hat{A}^{-1}b$ se tiene:

$$\hat{A}\hat{x} = b$$

$$(A+\Delta A)(x+\Delta x) = b$$

$$Ax + A \Delta x + \Delta Ax + \Delta A \Delta x = b$$

$$b + A \Delta x + \Delta A x = b$$

Donde en esta última ecuación se supuso que $\Delta A \Delta x \approx 0$ y de aquí:

$$A \Delta x + \Delta A x  \approx 0 \therefore \Delta x \approx - A^{-1} \Delta A x.$$

Entonces se tiene que la condición del problema $f$ calcular la solución de sistema de ecuaciones lineales $Az=b$ con $A$ no singular ante perturbaciones en $A$ es:

$$\text{Cond}_f^R = \frac{\frac{||x-\hat{x}||}{||x||}}{\frac{||A-\hat{A}||}{||A||}}=\frac{\frac{||\Delta x||}{||x||}}{\frac{||\Delta A||}{||A||}} \leq \frac{\frac{||A^{-1}||||\Delta Ax||}{||x||}}{\frac{||\Delta A||}{||A||}} \leq ||A^{-1}||||A||.$$

**Para responder la segunda pregunta...**

El número de condición de una matriz mide la sensibilidad de la solución de un sistema de ecuaciones lineales ante perturbaciones en los datos de entrada (en la matriz del sistema $A$ o en el lado derecho $b$). Si pequeños cambios en los datos de entrada generan grandes cambios en la solución tenemos un **sistema mal condicionado**. Si pequeños cambios en los datos de entrada generan pequeños cambios en la solución tenemos un sistema **bien condicionado**. Lo anterior puede apreciarse con los siguientes ejemplos y dibujo:

1.Resolver los siguientes sistemas:

$$a) \begin{array}{ccc} x_1 +2x_2   &= & 10 \\ 1.1x_1 + 2x_2 &= & 10.4 \end{array} $$

$$b)\begin{array}{ccc} 1.05x_1 +2x_2  &= & 10 \\ 1.1x_1 + 2x_2 &= & 10.4\end{array} $$

In [8]:
import numpy as np
import pprint

In [9]:
print('inciso a')
A = np.array([[1, 2], [1.1, 2]])
b = np.array([10,10.4])
print('A:')
pprint.pprint(A)
print('b:')
pprint.pprint(b)

inciso a
A:
array([[1. , 2. ],
       [1.1, 2. ]])
b:
array([10. , 10.4])


In [10]:
x=np.linalg.solve(A,b)
print('x:')
pprint.pprint(x)

x:
array([4., 3.])


In [11]:
print('inciso b')
A = np.array([[1.05, 2], [1.1, 2]])
b = np.array([10,10.4])
print('A:')
pprint.pprint(A)
print('b:')
pprint.pprint(b)

inciso b
A:
array([[1.05, 2.  ],
       [1.1 , 2.  ]])
b:
array([10. , 10.4])


In [12]:
x=np.linalg.solve(A,b)
print('x:')
pprint.pprint(x)

x:
array([8. , 0.8])


2.Resolver los siguientes sistemas:
    
$$a) \begin{array}{ccc} .03x_1 + 58.9x_2   &= & 59.2 \\ 5.31x_1 -6.1x_2 &= & 47 \end{array} $$

$$a) \begin{array}{ccc} .03x_1 + 58.9x_2   &= & 59.2 \\ .03x_1 -6.05x_2 &= & 47 \end{array} $$

In [13]:
print('inciso a')
A = np.array([[.03, 58.9], [5.31, -6.1]])
b = np.array([59.2,47])
print('A:')
pprint.pprint(A)
print('b:')
pprint.pprint(b)

inciso a
A:
array([[ 3.00e-02,  5.89e+01],
       [ 5.31e+00, -6.10e+00]])
b:
array([59.2, 47. ])


In [14]:
x=np.linalg.solve(A,b)
print('x:')
pprint.pprint(x)

x:
array([10.,  1.])


In [15]:
print('inciso b')
A = np.array([[.03, 58.9], [5.31, -6.05]])
b = np.array([59.2,47])
print('A:')
pprint.pprint(A)
print('b:')
pprint.pprint(b)

inciso b
A:
array([[ 3.00e-02,  5.89e+01],
       [ 5.31e+00, -6.05e+00]])
b:
array([59.2, 47. ])


In [16]:
x=np.linalg.solve(A,b)
print('x:')
pprint.pprint(x)

x:
array([9.99058927, 1.00000479])


3.Dibujo

<p align="centered">
<img src="https://drive.google.com/uc?export=view&id=1s0urIjJk_feDzHzslcX7u7mcFnXUcli8" alt="a" heigth="500" width="500">
</p>


**Comentario:** también para un sistema mal condicionado se considera que un amplio rango de valores en un SPFN satisface el mismo de forma aproximada.

---

## Norma

Una norma define una medida de distancia en un conjunto y da nociones de tamaño, vecindad, convergencia y continuidad.

**Normas vectoriales**

Sea $\mathbb{R}^n$ el conjunto de $n$-tuplas o vectores columna o $1$-arreglo de orden $1$, esto es:

$$x \in \mathbb{R}^n \iff x = \left[\begin{array}{c}
    x_1\\
    x_2\\
    \vdots\\
    x_n
    \end{array} \right] \text{ con } x_i \in \mathbb{R}$$
 

Una norma vectorial en $\mathbb{R}^n$ es una función $g: \mathbb{R}^n \rightarrow \mathbb{R}$ que satisface las siguientes propiedades:

* $g$ es no negativa: $g(x) \geq 0 \forall x \in \mathbb{R}^n$.

* $g$ es definida: $g(x) = 0 \iff x = 0$.

* $g$ satisface la desigualdad del triángulo: $$g(x+y) \leq g(x) + g(y) \forall x,y \in \mathbb{R}^n.$$


* $g$ es homogénea: $g(\alpha x)=|\alpha|g(x), \forall \alpha \in \mathbb{R}, \forall x \in \mathbb{R}^n$.

Notación: $g(x) = ||x||$.

**Comentarios:**

* Una norma es una generalización del valor absoluto de $\mathbb{R}$: $|x|, x \in \mathbb{R}.$

* Un espacio vectorial con una norma definida en éste se le llama **espacio vectorial normado**.

* Una norma es una medida de la longitud de un vector.

* Con una norma es posible definir conceptos como distancia entre vectores: $x,y \in \mathbb{R}^n: \text{dist}(x,y) = ||x-y||$.

* Existen varias normas en $\mathbb{R}^n$ siendo las más comunes:

 * La norma $\mathcal{l}_2$, Euclidiana o norma $2$: $||x||_2$.
 
 * La norma $\mathcal{l}_1$ o norma $1$: $||x||_1$.
 
 * La norma $\infty$ o de Chebyshev o norma infinito: $||x||_\infty$.
 
 Las normas anteriores pertenecen a una familia parametrizada por una constante $p, p \geq 1$ cuyo nombre es norma $\mathcal{l}_p$:
 
 $$ ||x||_p = \left(\displaystyle \sum_{i=1}^n|x_i|^p \right )^{1/p}.$$
 


->La norma $\infty$ se encuentra en esta familia como límite: 

$$||x||_\infty = \displaystyle \lim_{p \rightarrow \infty} ||x||_p.$$

->En la norma $\mathcal{l}_2$ o Euclidiana $||x||_2$ tenemos una desigualdad muy importante, la desigualdad de **Cauchy-Schwartz**:

$$|x^Ty| \leq ||x||_2||y||_2 \forall x,y \in \mathbb{R}^n$$

la cual relaciona el producto interno estándar para $x,y \in \mathbb{R}^n$: $<x,y> = x^Ty = \displaystyle \sum_{i=1}^nx_iy_i$ con la norma $\mathcal{l}_2$ de $x$ y la norma $\mathcal{l}_2$ de $y$. Además se utiliza lo anterior para definir el ángulo (sin signo) entre $x,y$: 

$$\measuredangle x,y = \cos ^{-1}\left(\frac{x^Ty}{||x||_2||y||_2} \right )$$

para $\cos^{-1}(u) \in [0,\pi]$ y se nombra a $x,y$ ortogonales si $x^Ty=0$. Obsérvese que $||x||_2 = \sqrt{x^Tx}$.

* También se utilizan matrices* para definir normas

*Matriz: arreglo $2$-dimensional de datos o $2$ arreglo de orden $2$. Se utiliza la notación $A \in \mathbb{R}^{m\times n}$ para denotar:


$$A = \left[\begin{array}{cccc}
a_{11} &a_{12}&\dots&a_{1n}\\
a_{21} &a_{22}&\dots&a_{2n}\\
\vdots &\vdots& \vdots&\vdots\\
a_{n1} &a_{n2}&\dots&a_{nn}\\
\vdots &\vdots& \vdots&\vdots\\
a_{m-11} &a_{m-12}&\dots&a_{m-1n}\\
a_{m1} &a_{m2}&\dots&a_{mm}
\end{array}
\right] 
$$


*$a_{ij} \mathbb{R} \forall i=1,\dots,m, j=1,\dots,n$.

*$A=(a_1,\dots a_n), a_j \in \mathbb{R}^m (=\mathbb{R}^{m\times1}) \forall j=1,\dots,n$.

*$A=\left ( \begin{array}{c}
a_1^T\\
\vdots\\
a_m^T
\end{array} \right ), a_i \in \mathbb{R}^n (=\mathbb{R}^{n\times1}) \forall i=1,\dots,m$.

**Ejercicios**

1. Resuelve los ejercicios y preguntas de la nota.

**Preguntas de comprehensión**

1)¿Qué factores influyen en la falta de exactitud de un cálculo?

2)Menciona $5$ propiedades que un conjunto debe cumplir para que sea considerado un espacio vectorial.

3)Menciona las propiedades que debe cumplir una función para que se considere una norma.

4)¿Qué es una norma matricial inducida?, ¿qué mide una norma matricial inducida?

5)¿La norma de Frobenius, es una norma matricial inducida?

6)¿A qué son iguales $\text{sup}(\emptyset)$, $\text{inf}(\emptyset)$ ? (el conjunto $\emptyset$ es el conjunto vacío)

7)Si f es un problema mal condicionado, ¿a qué nos referimos? Da ejemplos de problemas bien y mal condicionados.

8)Si f es un problema que resolvemos con un algoritmo g, ¿qué significa:

    a. que g sea estable?
    
    b. que g sea estable hacia atrás?
    
    c. que g sea inestable?
    
9)¿Qué ventaja(s) se tiene(n) al calcular un error hacia atrás vs calcular un error hacia delante?



**Referencias**

1. Nota [1.2.Sistema_de_punto_flotante](https://github.com/ITAM-DS/analisis-numerico-computo-cientifico/blob/master/temas/I.computo_cientifico/1.2.Sistema_de_punto_flotante.ipynb)

2. L. Trefethen, D. Bau, Numerical linear algebra, SIAM, 1997.