(AAEVALEVEC)=

# 2.3 Algoritmos y aplicaciones de eigenvalores y eigenvectores de una matriz

```{admonition} Notas para contenedor de docker:

Comando de docker para ejecución de la nota de forma local:

nota: cambiar `<ruta a mi directorio>` por la ruta de directorio que se desea mapear a `/datos` dentro del contenedor de docker.

`docker run --rm -v <ruta a mi directorio>:/datos --name jupyterlab_optimizacion -p 8888:8888 -d palmoreck/jupyterlab_optimizacion:2.1.4`

password para jupyterlab: `qwerty`

Detener el contenedor de docker:

`docker stop jupyterlab_optimizacion`

Documentación de la imagen de docker `palmoreck/jupyterlab_optimizacion:2.1.4` en [liga](https://github.com/palmoreck/dockerfiles/tree/master/jupyterlab/optimizacion).

```

---

Nota generada a partir de [liga](https://www.dropbox.com/s/s4ch0ww1687pl76/3.2.2.Factorizaciones_matriciales_SVD_Cholesky_QR.pdf?dl=0).

## Rotaciones de Jacobi para matrices simétricas

Este método produce una secuencia de transformaciones ortogonales de la forma $J_k^TAJ_k$ con el objetivo de hacer "más diagonal" a la matriz $A \in \mathbb{R}^{n \times n}$.

En el algoritmo se hace mención sobre **metodologías** que ayudan a elegir los índices del renglón y columna de $A$ que serán eliminadas. Algunas de éstas son:

1.Elegir $(idx1,idx2)$ tales que $|a_{idx1,idx2}| = \displaystyle \max_{i \neq j}|a_{ij}|$.

2.**Ordenamiento cíclico por renglones:** elegir $(idx1, idx2)$ en el conjunto $(1,2),(1,3),\dots,(1,n),(2,3),(2,4)\dots,(n-1,n)$.

```{margin}

Los pasos de este algoritmo representan una guía para la implementación. Al describirse los pasos de un algoritmo no implica que se tengan que implementar uno a continuación del otro como se describe. Si una implementación respeta la lógica y al mismo método, entonces pueden seguirse los pasos de una forma distinta.
```

> **Algoritmo de rotaciones de Jacobi para matrices simétricas**
>>
>> **Dada** $A$ simétrica y $tol$ **definir** $A_0 = A$, $V_0 = I_n$.
>>
>> **Repetir** el siguiente bloque para $k=0,1,2,\dots$
>>> 1. Elegir un par de índices $(idx1,idx2)$ con alguna de las metodologías descritas anteriormente.
>>>
>>> 2. Calcular las entradas $\cos(\theta),\sin(\theta)$ de la matriz de rotación $J_k$.
>>>
>>> 3. $A_{k+1} = J_k^T A_k J_k$
>>>
>>> 4. $V_{k+1} = V_{k}J_k$.
>>
>> **hasta** convergencia (satisfacer criterio de paro).



La matriz $J_k$ es una transformación de rotación que se utiliza para eliminar un par de entradas (simétricas) en la matriz $A_k$, esto  preserva la simetría de la matriz original, ver {ref}`transformaciones de rotación <TROT>`. En las columnas de la matriz $V_{k}$ se encuentran aproximaciones a los eigenvectores de $A$ y en la diagonal de $A_{k}$ se tienen aproximaciones a los eigenvalores de $A$.

```{admonition} Observación
:class: tip

Obsérvese que $A_{k+1}$ y $A_{k}$ son matrices similares, ver {ref}`similitud <SIMILITUD>`.

```

Para encontrar la forma que debe tener $J_k$ es suficiente considerar el caso $2 \times 2$ y se **asume** que $a_{12} \neq 0$ pues **si $a_{12} =0$ entonces no hay que realizar rotación**:

$$
\begin{eqnarray}
J_k^TAJ_k &=&  
\left [
\begin{array}{cc}
c & -s\\
s & c
\end{array}
\right ]
\left [
\begin{array}{cc}
a_{11} & a_{12}\\
a_{12} & a_{22}
\end{array}
\right ]
\left [
\begin{array}{cc}
c & s\\
-s & c
\end{array}
\right ]
\nonumber \\
&=&
\left [
\begin{array}{cc}
c^2a_{11} -2 csa_{12} + s^2a_{22} & c^2a_{12} - cs(a_{22}-a_{11})-s^2a_{12}\nonumber \\
c^2a_{12} - cs(a_{22}-a_{11})-s^2a_{12} & c^2a_{22}+2csa_{12}+s^2a_{11} \nonumber
\end{array}
\right ]
\nonumber 
\end{eqnarray}
$$

donde: $c$ y $s$ representan a $\cos(\theta), \sin(\theta)$ respectivamente y $\theta$ ángulo para rotar.


Si se desea que la entrada $(1,2)$ (equivalentemente por simetría la $(2,1)$) sea cero se debe cumplir:

$$c^2a_{12} - cs(a_{22}-a_{11})-s^2a_{12}=0.$$

Asignando la variable $t = \frac{s}{c}$ (tangente de $\theta$) se obtiene la ecuación cuadrática:

$$1 - t\frac{(a_{22}-a_{11})}{a_{12}} - t^2 = 0.$$

Equivalentemente:

$$t^2 + t\frac{(a_{22}-a_{11})}{a_{12}} - 1 = t^2 + 2\tau t -1 = 0$$


```{margin}

Las funciones $\frac{1}{\tau+\sqrt{\tau^2+1}}$, $\frac{1}{\tau-\sqrt{\tau^2+1}}$ son estrictamente decrecientes para $\tau \geq 0$ y $\tau < 0$ respectivamente. Un valor de $\tau$ corresponde a un único ángulo $\theta \in \left [-\frac{\pi}{4}, \frac{\pi}{4} \right ]$.
```

donde: $\tau = \frac{a_{22}-a_{11}}{2a_{12}}$. Las raíces de la ecuación anterior están dadas por:

$$
\begin{eqnarray}
t_1^* &=& -\tau + \sqrt{\tau^2+1}&=&\frac{1}{\tau+\sqrt{\tau^2+1}} \nonumber \\
t_2^* &=& -\tau - \sqrt{\tau^2+1}&=&\frac{1}{\tau-\sqrt{\tau^2+1}} \nonumber
\end{eqnarray}
$$


Se **sugiere** utilizar la raíz de menor magnitud para disminuir errores por redondeo por lo que:

$$t^* = \frac{\text{signo}(\tau)}{|\tau| + \sqrt{1+\tau^2}}$$

donde:

$$
\text{signo}(x) = \begin{cases}
1 \text{ si } x>=0\\
-1 \text{ en otro caso}
\end{cases}
$$

Las relaciones entre coseno, seno y tangente permiten obtener sus valores correspondientes:

$$c = \frac{1}{\sqrt{1+t^{*2}}},$$

$$s = ct^*$$

y así tener completamente definida a la matriz $J_k$.

### Ejemplo

Considera: 

$$
A = 
\left [
\begin{array}{cc}
1&2\\
2&1\\
\end{array}
\right ].
$$

Eliminar las entradas $(1,2)$ y $(2,1)$ con una matriz $J$ de rotación de Jacobi:

In [1]:
import numpy as np

In [2]:
np.set_printoptions(precision=3, suppress=True)

In [3]:
A = np.array([[1,2],
              [2,1]])

In [4]:
def sign(x):
    """
    Help function for computing sign of real number x.
    """
    if x >=0:
        return 1
    else:
        return -1

In [5]:
A_k = A.copy()

In [6]:
def compute_cos_sin_Jacobi_rotation(Ak, idx1, idx2):
    """
    Help function for computing entries of Jacobi rotation.
    Args:
        Ak (numpy ndarray): Matrix of iteration k in Jacobi rotation method.
        idx1 (int): index for rows in Jacobi rotation matrix.
        idx2 (int): index for columns in Jacobi rotation matrix.
    Returns:
        c (float): value of cos of theta for Jacobi rotation matrix.
        s (float): value of sin of theta for Jacobi rotation matrix.
    """
    if np.abs(Ak[idx1,idx2]) > np.finfo(float).eps:
        tau = (Ak[idx2, idx2] - Ak[idx1, idx1])/(2*Ak[idx1, idx2])
        t_star = sign(tau)/(np.abs(tau) + np.sqrt(1+tau**2))
        c = 1/np.sqrt(1+t_star**2)
        s = c*t_star
    else:
        c = 1
        s = 0
    return (c,s)

```{margin}

Estos son los índices que corresponden a la entrada $a_{12}$ de $A$.

```

In [7]:
idx_1 = 0
idx_2 = 1

In [8]:
c, s = compute_cos_sin_Jacobi_rotation(A_k, idx_1, idx_2)

```{margin}

La matriz de rotación de Jacobi es en este caso de tamaño $2 \times 2$.

```

In [9]:
J = np.array([[c, s],
              [-s, c]])

In [10]:
J.T@A@J

array([[-1.,  0.],
       [ 0.,  3.]])

Por construcción $A$ y $J^TAJ$ son similares y por tanto tienen el mismo espectro:

In [11]:
np.linalg.eigvalsh(A)

array([-1.,  3.])

In [12]:
np.linalg.eigvalsh(J.T@A@J)

array([-1.,  3.])

Ver [eigvals](https://numpy.org/doc/stable/reference/generated/numpy.linalg.eigvals.html) y [eigvalsh](https://jiffyclub.github.io/numpy/reference/generated/numpy.linalg.eigvalsh.html).

```{admonition} Comentarios

El algoritmo de rotaciones de Jacobi utiliza como criterios de paro:

* La cantidad $\text{off}(A) = \sqrt{\displaystyle \sum_{i=1}^n \sum_{j=1, j\neq i}^n a_{ij}^2}$ que es la norma de Frobenius de $A$ sin la diagonal.

* Número máximo de *sweeps*. Un *sweep* es igual a $\frac{n(n-1)}{2}$ y corresponde al número máximo de entradas de la matriz que forman la parte triangular superior de $A$ (sin contar a la diagonal) que se asumen diferentes de cero. No existe teoría rigurosa para el número de *sweeps* pero una heurística encontrada por [Brent y Luk, p. 13, 1985](https://ecommons.cornell.edu/handle/1813/6402) menciona que el número máximo es proporcional a $\mathcal{O}(\log(n))$ y en la práctica se utilizan entre $6$ y $10$, ver [H. Rutishauser, The Jacobi method for real symmetric matrices, 1966](https://link.springer.com/article/10.1007/BF02165223).

```

## Ejemplo

Considera: 

$$
A = 
\left [
\begin{array}{cccc}
1 & 2 & 3 & 4\\
2 & -2 & 4 & 5\\
3 & 4 & 6 & 7\\
4 & 5 & 7 & -8
\end{array}
\right ].
$$

Utilizando la metodología de ordenamiento cíclico por renglones realizar dos *sweeps* del método de rotaciones de Jacobi.

In [13]:
def compute_Jacobi_rotation(Ak, idx1, idx2):
    """
    Compute Jacobi rotation matrix.
    Args:
        Ak (numpy ndarray): Matrix of iteration k in Jacobi rotation method.
        idx1 (int): index for rows in Jacobi rotation matrix.
        idx2 (int): index for columns in Jacobi rotation matrix.
    Returns:
        J (numpy ndarray): Jacobi rotation matrix.
    """
    c,s = compute_cos_sin_Jacobi_rotation(Ak, idx1, idx2)
    m,n = Ak.shape
    J = np.eye(m)
    J[idx1, idx1] = J[idx2, idx2] = c
    J[idx1, idx2] = s
    J[idx2, idx1] = -s
    return J

In [14]:
A = np.array([[1,2,3,4],
              [2,-2,4,5],
              [3, 4, 6, 7],
              [4, 5, 7,-8.0]])

In [15]:
A

array([[ 1.,  2.,  3.,  4.],
       [ 2., -2.,  4.,  5.],
       [ 3.,  4.,  6.,  7.],
       [ 4.,  5.,  7., -8.]])

In [16]:
A_k = A.copy()

El **primer *sweep*** considera las entradas: $(1,2), (1,3), (1,4), (2,3), (2,4), (3,4)$ y se toman a continuación en el orden $(1,4), (1,3), (1,2), (2,4), (2,3)$ y finalmente $(3,4)$ para mostrar que el orden de selección de las entradas no importa.

**Entrada $a_{41}$ plano $(1,4)$:**

In [17]:
idx_1 = 0
idx_2 = 3
J = compute_Jacobi_rotation(A_k, idx_1, idx_2)

In [18]:
A_k = J.T@A_k@J

In [19]:
print(A_k)

[[ 2.521  3.646  5.292 -0.   ]
 [ 3.646 -2.     4.     3.963]
 [ 5.292  4.     6.     5.477]
 [ 0.     3.963  5.477 -9.521]]


**Entrada $a_{31}$ plano $(1,3)$:**

In [20]:
idx_1 = 0
idx_2 = 2
J = compute_Jacobi_rotation(A_k, idx_1, idx_2)

In [21]:
A_k = J.T@A_k@J

In [22]:
print(A_k)

[[-1.31   0.608 -0.    -3.212]
 [ 0.608 -2.     5.378  3.963]
 [-0.     5.378  9.831  4.436]
 [-3.212  3.963  4.436 -9.521]]


**Entrada $a_{21}$ plano $(1,2)$:**

In [23]:
idx_1 = 0
idx_2 = 1
J = compute_Jacobi_rotation(A_k, idx_1, idx_2)

In [24]:
A_k = J.T@A_k@J

In [25]:
print(A_k)

[[-0.956  0.     2.707 -0.781]
 [ 0.    -2.354  4.648  5.041]
 [ 2.707  4.648  9.831  4.436]
 [-0.781  5.041  4.436 -9.521]]


**Entrada $a_{42}$ plano $(2,4)$:**

In [26]:
idx_1 = 1
idx_2 = 3
J = compute_Jacobi_rotation(A_k, idx_1, idx_2)

In [27]:
A_k = J.T@A_k@J

In [28]:
print(A_k)

[[ -0.956  -0.358   2.707  -0.694]
 [ -0.358   0.247   6.165   0.   ]
 [  2.707   6.165   9.831   1.811]
 [ -0.694   0.      1.811 -12.122]]


**Entrada $a_{32}$ plano $(2,3)$:**

In [29]:
idx_1 = 1
idx_2 = 2
J = compute_Jacobi_rotation(A_k, idx_1, idx_2)

In [30]:
A_k = J.T@A_k@J

In [31]:
print(A_k)

[[ -0.956  -1.511   2.274  -0.694]
 [ -1.511  -2.769  -0.     -0.796]
 [  2.274   0.     12.847   1.627]
 [ -0.694  -0.796   1.627 -12.122]]


**Entrada $a_{43}$ plano $(3,4)$:**

In [32]:
idx_1 = 2
idx_2 = 3
J = compute_Jacobi_rotation(A_k, idx_1, idx_2)

In [33]:
A_k = J.T@A_k@J

In [34]:
print(A_k)

[[ -0.956  -1.511   2.224  -0.84 ]
 [ -1.511  -2.769  -0.052  -0.794]
 [  2.224  -0.052  12.952   0.   ]
 [ -0.84   -0.794   0.    -12.228]]


**Segundo *sweep***

**Entrada $a_{41}$ plano $(1,4)$:**

In [35]:
idx_1 = 0
idx_2 = 3
J = compute_Jacobi_rotation(A_k, idx_1, idx_2)

In [36]:
A_k = J.T@A_k@J

In [37]:
print(A_k)

[[ -0.894  -1.448   2.218  -0.   ]
 [ -1.448  -2.769  -0.052  -0.904]
 [  2.218  -0.052  12.952   0.164]
 [ -0.     -0.904   0.164 -12.29 ]]


**Entrada $a_{31}$ plano $(1,3)$:**

In [38]:
idx_1 = 0
idx_2 = 2
J = compute_Jacobi_rotation(A_k, idx_1, idx_2)

In [39]:
A_k = J.T@A_k@J

In [40]:
print(A_k)

[[ -1.24   -1.423   0.     -0.025]
 [ -1.423  -2.769  -0.275  -0.904]
 [ -0.     -0.275  13.299   0.162]
 [ -0.025  -0.904   0.162 -12.29 ]]


**Entrada $a_{21}$ plano $(1,2)$:**

In [41]:
idx_1 = 0
idx_2 = 1
J = compute_Jacobi_rotation(A_k, idx_1, idx_2)

In [42]:
A_k = J.T@A_k@J

In [43]:
print(A_k)

[[ -0.389  -0.      0.141   0.442]
 [  0.     -3.62   -0.236  -0.789]
 [  0.141  -0.236  13.299   0.162]
 [  0.442  -0.789   0.162 -12.29 ]]


**Entrada $a_{42}$ plano $(2,4)$:**

In [44]:
idx_1 = 1
idx_2 = 3
J = compute_Jacobi_rotation(A_k, idx_1, idx_2)

In [45]:
A_k = J.T@A_k@J

In [46]:
print(A_k)

[[ -0.389  -0.04    0.141   0.44 ]
 [ -0.04   -3.549  -0.249   0.   ]
 [  0.141  -0.249  13.299   0.141]
 [  0.44    0.      0.141 -12.361]]


**Entrada $a_{32}$ plano $(2,3)$:**

In [47]:
idx_1 = 1
idx_2 = 2
J = compute_Jacobi_rotation(A_k, idx_1, idx_2)

In [48]:
A_k = J.T@A_k@J

In [49]:
print(A_k)

[[ -0.389  -0.038   0.141   0.44 ]
 [ -0.038  -3.552   0.      0.002]
 [  0.141   0.     13.303   0.141]
 [  0.44    0.002   0.141 -12.361]]


**Entrada $a_{43}$ plano $(3,4)$:**

In [50]:
idx_1 = 2
idx_2 = 3
J = compute_Jacobi_rotation(A_k, idx_1, idx_2)

In [51]:
A_k = J.T@A_k@J

In [52]:
print(A_k)

[[ -0.389  -0.038   0.144   0.44 ]
 [ -0.038  -3.552   0.      0.002]
 [  0.144   0.     13.304   0.   ]
 [  0.44    0.002   0.    -12.362]]


**Nuevo *sweep*** ...

```{admonition} Ejercicio
:class: tip

Programar la función `Jacobi_rotations` para diagonalizar a la matriz simétrica del ejemplo anterior y para la matriz:

$$
A = 
\left [
\begin{array}{ccc}
1 & 0 & 2\\
0 & 2 & 1\\
2 & 1 & 1
\end{array}
\right ]
$$
```

## Algoritmo QR

## Método de la potencia

## Aplicaciones y usos

Ver comentario sobre Schur en https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html

https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.schur.html#scipy.linalg.schur

In [2]:
from scipy.linalg import schur, eigvals
import numpy as np

In [3]:
A = np.array([[0, 2, 2], [0, 1, 2], [1, 0, 1]])

In [4]:
T, Z = schur(A)

In [5]:
T

array([[ 2.65896708,  1.42440458, -1.92933439],
       [ 0.        , -0.32948354, -0.49063704],
       [ 0.        ,  1.31178921, -0.32948354]])

In [6]:
evalue, evector = np.linalg.eig(T)

In [7]:
with np.printoptions(precision=3, suppress=True):
    print(evector)

[[1.   +0.j    0.497-0.081j 0.497+0.081j]
 [0.   +0.j    0.   +0.451j 0.   -0.451j]
 [0.   +0.j    0.737+0.j    0.737-0.j   ]]


In [8]:
print(evalue)

[ 2.65896708+0.j         -0.32948354+0.80225456j -0.32948354-0.80225456j]


In [9]:
A2 = T[1:3, 1:3]

In [10]:
A2

array([[-0.32948354, -0.49063704],
       [ 1.31178921, -0.32948354]])

In [11]:
evalue, evector = np.linalg.eig(A2)

In [12]:
evalue

array([-0.32948354+0.80225456j, -0.32948354-0.80225456j])

**Referencias:**

1. M. T. Heath, Scientific Computing. An Introductory Survey, McGraw-Hill, 2002.

2.  G. H. Golub, C. F. Van Loan, Matrix Computations, John Hopkins University Press, 2013.

3. L. Trefethen, D. Bau, Numerical linear algebra, SIAM, 1997.

4. C. Meyer, Matrix Analysis and Applied Linear Algebra, SIAM, 2000.