```{admonition} Notas para contenedor de docker:

Comando de docker para ejecución de la nota de forma local:

nota: cambiar `<ruta a mi directorio>` por la ruta de directorio que se desea mapear a `/datos` dentro del contenedor de docker.

`docker run --rm -v <ruta a mi directorio>:/datos --name jupyterlab_optimizacion -p 8888:8888 -d palmoreck/jupyterlab_optimizacion:2.1.4`

password para jupyterlab: `qwerty`

Detener el contenedor de docker:

`docker stop jupyterlab_optimizacion`

Documentación de la imagen de docker `palmoreck/jupyterlab_optimizacion:2.1.4` en [liga](https://github.com/palmoreck/dockerfiles/tree/master/jupyterlab/optimizacion).

```

---

Nota generada a partir de [liga1](https://www.dropbox.com/s/fyqwiqasqaa3wlt/3.1.1.Multiplicacion_de_matrices_y_estructura_de_datos.pdf?dl=0), [liga2](https://www.dropbox.com/s/jwu8lu4r14pb7ut/3.2.1.Sistemas_de_ecuaciones_lineales_eliminacion_Gaussiana_y_factorizacion_LU.pdf?dl=0) y [liga3](https://www.dropbox.com/s/s4ch0ww1687pl76/3.2.2.Factorizaciones_matriciales_SVD_Cholesky_QR.pdf?dl=0).

# 2.1 Operaciones y transformaciones básicas del Álgebra Lineal Numérica

Las operaciones básicas del Álgebra Lineal Numérica podemos dividirlas en vectoriales y matriciales.

## Vectoriales

* **Transponer:** $\mathbb{R}^{n \times 1}  \rightarrow \mathbb{R} ^{1 \times n}$: $y = x^T$ entonces

$$x = 
\left[
\begin{array}{c}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{array}
\right ]
$$
y se tiene:

$$ y = x^T = [x_1, x_2, \dots, x_n].$$

* **Suma:** $\mathbb{R}^n  \times \mathbb{R} ^n \rightarrow \mathbb{R}^n$: $z = x + y $ entonces $z_i = x_i + y_i$

* **Multiplicación por un escalar:** $\mathbb{R} \times \mathbb{R} ^n \rightarrow \mathbb{R}^n$: $y = \alpha x$ entonces $y_i = \alpha x_i$.

* **Producto interno estándar o producto punto:** $\mathbb{R}^n \times \mathbb{R} ^n \rightarrow \mathbb{R}$: $c = x^Ty$ entonces $c = \displaystyle \sum_{i=1}^n x_i y_i$.


* **Multiplicación *point wise:*** $\mathbb{R}^n \times \mathbb{R} ^n \rightarrow \mathbb{R}^n$: $z = x.*y$ entonces $z_i = x_i y_i$.

* **División *point wise:*** $\mathbb{R}^n \times \mathbb{R} ^n \rightarrow \mathbb{R}^n$: $z = x./y$ entonces $z_i = x_i /y_i$ con $y_i \neq 0$.


* **Producto exterior o *outer product*:** $\mathbb{R}^n \times \mathbb{R} ^n \rightarrow \mathbb{R}^{n \times n}$: $A = xy^T$ entonces $A[i, :] = x_i y^T$ con $A[i,:]$ es el $i$-ésimo renglón de $A$.

## Matriciales


* **Transponer:** $\mathbb{R}^{m \times n} \rightarrow \mathbb{R}^{n \times m}$: $C = A^T$ entonces $c_{ij} = a_{ij}$.

* **Sumar:** $\mathbb{R}^{m \times n} \times \mathbb{R}^{m \times n} \rightarrow \mathbb{R}^{m \times n}$: $C = A + B$ entonces $c_{ij} = a_{ij} + b_{ij}$.

* **Multiplicación por un escalar:** $\mathbb{R} \times \mathbb{R}^{m \times n} \rightarrow \mathbb{R}^{m \times n}$: $C = \alpha A$ entonces $c_{ij} = \alpha a_{ij}$

* **Multiplicación por un vector:** $\mathbb{R}^{m \times n} \times \mathbb{R}^{n} \rightarrow \mathbb{R}^{m}$: $y = Ax$ entonces $y_i = \displaystyle \sum_{j=1}^n a_{ij}x_j$.

* **Multiplicación entre matrices:** $\mathbb{R}^{m \times k} \times \mathbb{R}^{k \times n} \rightarrow \mathbb{R}^{m \times n}$: $C = AB$ entonces $c_{ij} = \displaystyle \sum_{r=1}^k a_{ir}b_{rj}$.

* **Multiplicación *point wise*:** $\mathbb{R}^{m \times n} \times \mathbb{R}^{m \times n} \rightarrow \mathbb{R}^{m \times n}$: $C = A.*B$ entonces $c_{ij} = a_{ij}b_{ij}$.


* **División *point wise*:** $\mathbb{R}^{m \times n} \times \mathbb{R}^{m \times n} \rightarrow \mathbb{R}^{m \times n}$: $C = A./B$ entonces $c_{ij} = a_{ij}/b_{ij}$ con $b_{ij} \neq 0$.



Como ejemplos de transformaciones básicas del Álgebra Lineal Numérica se encuentran:

In [1]:
import numpy as np

## Transformaciones de Gauss

En esta sección suponemos que $A \in \mathbb{R}^{n \times n}$ y $A$ es una matriz con entradas $a_{ij} \in \mathbb{R}^{n \times n} \forall i,j=1,2,\dots,n$.

Considérese al vector $a \in \mathbb{R}^{n}$ y $e_k \in \mathbb{R}^n$ el $k$-ésimo vector canónico: vector con un $1$ en la posición $k$ y ceros en las entradas restantes.

Una transformación de Gauss está definida de forma general como $L_k = I_n - \ell_ke_k^T$ con $\ell_k = (0,0,\dots,\ell_{k+1,k},\dots,\ell_{n,k})^T$ y $\ell_{i,k}=\frac{a_{ik}}{a_{kk}} \forall i=k+1,\dots,n$.

Las transformaciones de Gauss se utilizan para hacer ceros por debajo del **pivote**.

### Ejemplo aplicando transformaciones de Gauss a un vector

Considérese al vector $a=(-2,3,4)^T$. Definir una transformación de Gauss para hacer ceros por debajo de $a_1$ y otra transformación de Gauss para hacer cero la entrada $a_3$

**Solución:**

a)Para hacer ceros por debajo del **pivote** $a_1 = -2$:

In [2]:
a = np.array([-2,3,4])

In [3]:
pivote = a[0]

```{margin} Recuerda
La definición de $l_1=(0, \frac{a_2}{a_1}, \frac{a_3}{a_1})^T$
```

In [4]:
l1 = np.array([0,a[1]/pivote, a[2]/pivote])

In [5]:
e1 = np.array([1,0,0])

```{margin}
**Observa que por la definición de la transformación de Gauss, no necesitamos construir a la matriz $L_1$.**
```

In [6]:
L1_a = a-l1*(e1.dot(a))

In [7]:
L1_a

array([-2.,  0.,  0.])

A continuación se muestra que el producto $L_1 a$ si se construye $L_1$ es equivalente a lo anterior:

In [9]:
L1 = np.eye(3) - np.outer(l1,e1)

In [10]:
L1

array([[1. , 0. , 0. ],
       [1.5, 1. , 0. ],
       [2. , 0. , 1. ]])

In [11]:
L1@a

array([-2.,  0.,  0.])

b) Para hacer ceros por debajo del **pivote** $a_2 = 3$:

In [11]:
a = np.array([-2,3,4])

In [12]:
pivote = a[1]

In [13]:
l2 = np.array([0,0, a[2]/pivote])

In [14]:
e2 = np.array([0,1,0])

```{admonition} Observación
:class: tip
Por la definición de la transformación de Gauss, no necesitamos construir a la matriz $L_2$.
```

In [15]:
L2_a = a-l2*(e2.dot(a))

In [16]:
L2_a

array([-2.,  3.,  0.])

A continuación se muestra que el producto $L_2 a$ si se construye $L_2$ es equivalente a lo anterior:

In [17]:
L2 = np.eye(3) - np.outer(l2,e2)

In [18]:
L2

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ],
       [ 0.        , -1.33333333,  1.        ]])

In [19]:
L2@a

array([-2.,  3.,  0.])

### Ejemplo aplicando transformaciones de Gauss a una matriz

Si tenemos una matriz $A \in \mathbb{R}^{3 \times 3}$ y queremos hacer ceros por debajo de su diagonal, realizamos los productos matriciales:

$$L_2 L_1 A$$

donde: $L_1, L_2$ son transformaciones de Gauss.

**Ejemplo:**

a) Utilizando $L_1$

In [20]:
A = np.array([[-1, 2, 5],
              [4, 5, -7],
              [3, 0, 8]])

In [21]:
A

array([[-1,  2,  5],
       [ 4,  5, -7],
       [ 3,  0,  8]])

Para hacer ceros por debajo del **pivote** $a_{11} = -1$:

In [22]:
pivote = A[0, 0]

In [23]:
l1 = np.array([0,A[1,0]/pivote, A[2,0]/pivote])

In [24]:
e1 = np.array([1,0,0])

**Obsérvese que por la definición de la transformación de Gauss, no necesitamos construir a la matriz $L_1$**

In [25]:
L1_A_1 = A[:,0]-l1*(e1.dot(A[:,0]))

In [26]:
L1_A_1

array([-1.,  0.,  0.])

**Y se debe aplicar $\ell_1$ a las columnas número 2 y 3 de $A$:**

In [27]:
L1_A_2 = A[:,1]-l1*(e1.dot(A[:,1]))

In [28]:
L1_A_2

array([ 2., 13.,  6.])

In [29]:
L1_A_3 = A[:,2]-l1*(e1.dot(A[:,2]))

In [30]:
L1_A_3

array([ 5., 13., 23.])

A continuación se muestra que el producto $L_1 A$ si se construye $L_1$ es equivalente a lo anterior:

In [31]:
L1 = np.eye(3) - np.outer(l1,e1)

In [32]:
L1

array([[1., 0., 0.],
       [4., 1., 0.],
       [3., 0., 1.]])

In [33]:
L1 @ A

array([[-1.,  2.,  5.],
       [ 0., 13., 13.],
       [ 0.,  6., 23.]])

**Obs:**

* Obsérvese que al aplicar $\ell_1$ a la primer columna de $A$ **siempre** obtenemos ceros por debajo del pivote que en este caso es $a_{11}$.

* Obsérvese que después de hacer la multiplicación $L_1A$ en cualquiera de los dos casos (construyendo o no explícitamente $L_1$) no se modifica el primer renglón de $A$:

In [34]:
A

array([[-1,  2,  5],
       [ 4,  5, -7],
       [ 3,  0,  8]])

In [35]:
A[0,:]

array([-1,  2,  5])

In [36]:
(L1 @ A)[0,:]

array([-1.,  2.,  5.])

por lo que la multiplicación $L_1A$ entonces modifica del segundo renglón de $A$ en adelante y de la segunda columna de $A$ en adelante.

* Obsérvese que dada la forma de $L_1 = I_n - \ell_1e_1^T$, al hacer la multiplicación por la segunda y tercer columna de $A$ se tiene:

$$e_1^T A[:,1] = A[0,1]$$

$$e_1^T A[:,2] = A[0,2]$$

In [37]:
e1.dot(A[:, 1])

2

In [38]:
e1.dot(A[:, 2])

5

y puede escribirse de forma compacta:

$$e_1^T A[:,1:2] = A[0, 1:2]$$

In [39]:
A[0, 1:3] #observe that we have to use 2+1=3 as the second number in 1:3

array([2, 5])

In [40]:
A[0, 1:] #also we could have use this statement

array([2, 5])

Entonces los productos $\ell_1 e_1^T A[:,1]$ y $\ell_1 e_1^T A[:,2]$ quedan respectivamente como:

$$\ell_1A[0, 1]$$

In [41]:
l1*A[0,1]

array([ 0., -8., -6.])

$\ell_1A[0,2]$

In [42]:
l1*A[0, 2]

array([  0., -20., -15.])

Obsérvese que las primeras entradas son iguales a $0$ por lo que es consistente con el hecho que únicamente se modifican dos entradas de la segunda y tercer columna de $A$.

De forma compacta se puede calcular lo anterior como:

In [43]:
np.outer(l1[1:3],A[0,1:3])

array([[ -8., -20.],
       [ -6., -15.]])

In [44]:
np.outer(l1[1:],A[0,1:]) #also we could have use this statement

array([[ -8., -20.],
       [ -6., -15.]])

Y finalmente la aplicación de $L_1$ al segundo renglón y segunda columna en adelante de $A$ queda:

In [45]:
A[1:3, 1:3] - np.outer(l1[1:3],A[0,1:3])

array([[13., 13.],
       [ 6., 23.]])

Practicando combinar columnas y renglones en *numpy* con [column_stack](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html) y *row_stack*:

In [46]:
A_aux = A[1:3, 1:3] - np.outer(l1[1:3],A[0,1:3])

In [47]:
m, n = A.shape
number_of_zeros = m-1
A_aux_2 = np.column_stack((np.zeros(number_of_zeros), A_aux)) # stack two zeros

In [48]:
A_aux_2

array([[ 0., 13., 13.],
       [ 0.,  6., 23.]])

In [49]:
A_aux_3 = np.row_stack((A[0, :], A_aux_2))

In [50]:
A_aux_3

array([[-1.,  2.,  5.],
       [ 0., 13., 13.],
       [ 0.,  6., 23.]])

que es el resultado de:

In [51]:
L1 @ A

array([[-1.,  2.,  5.],
       [ 0., 13., 13.],
       [ 0.,  6., 23.]])

**Ejercicio:** calcular el producto $L_2 L_1 A$ para la matriz anterior y para la matriz:

$$
A = \left [
\begin{array}{ccc}
1 & 4 & -2 \\
-3 & 9 & 8 \\
5 & 1 & -6
\end{array}
\right]
$$

## Transformaciones de proyección

## Transformaciones de reflexión