(EigValEigVec)=

# 2.2 Eigenvalores y eigenvectores

```{admonition} Notas para contenedor de docker:

Comando de docker para ejecución de la nota de forma local:

nota: cambiar `<ruta a mi directorio>` por la ruta de directorio que se desea mapear a `/datos` dentro del contenedor de docker.

`docker run --rm -v <ruta a mi directorio>:/datos --name jupyterlab_optimizacion -p 8888:8888 -d palmoreck/jupyterlab_optimizacion:2.1.4`

password para jupyterlab: `qwerty`

Detener el contenedor de docker:

`docker stop jupyterlab_optimizacion`

Documentación de la imagen de docker `palmoreck/jupyterlab_optimizacion:2.1.4` en [liga](https://github.com/palmoreck/dockerfiles/tree/master/jupyterlab/optimizacion).

```

---

Nota generada a partir de [liga](https://www.dropbox.com/s/s4ch0ww1687pl76/3.2.2.Factorizaciones_matriciales_SVD_Cholesky_QR.pdf?dl=0).

**En lo que sigue se asume que $A \in \mathbb{R}^{n \times n}$.**

## Definiciones y resultados generales

## Eigenvalor (valor propio o característico)

El número $\lambda$ (real o complejo) se denomina *eigenvalor* de A si existe $v \in \mathbb{C}^n - \{0\}$ tal que $Av = \lambda v$. El vector $v$ se nombra eigenvector (vector propio o característico) de $A$ correspondiente al eigenvalor $\lambda$.

```{admonition} Comentarios

* Una matriz con componentes reales puede tener eigenvalores y eigenvectores con valores en $\mathbb{C}$ o $\mathbb{C}^n$ respectivamente.
* El conjunto de eigenvalores se le llama **espectro de una matriz** y se denota como:

$$\lambda(A) = \{ \lambda | \det(A-\lambda I_n) = 0\}.$$

* La multiplicación de $A$ por un eigenvector es un reescalamiento y posible cambio de dirección del eigenvector.
* $A$ siempre tiene al menos un eigenvalor con eigenvector asociado.
* $A$ tiene $n$ eigenvalores y pueden o no repetirse.
* $\det(A) = \displaystyle \prod_{i=1}^n \lambda_i$, $tr(A) = \displaystyle \sum_{i=1}^n \lambda_i$.
```

**En *NumPy* con el módulo `eig` podemos obtener eigenvalores y eigenvectores** 

In [1]:
import numpy as np

### Ejemplo

In [2]:
A=np.array([[10,-18],[6,-11]])

In [3]:
A

array([[ 10, -18],
       [  6, -11]])

In [4]:
evalue, evector = np.linalg.eig(A)

In [5]:
print('eigenvalores:')
print(evalue)
print('eigenvectores:')
print(evector)

eigenvalores:
[ 1. -2.]
eigenvectores:
[[0.89442719 0.83205029]
 [0.4472136  0.5547002 ]]


Comprobamos: $Av_1 = \lambda_1 v_1$, $Av_2 = \lambda_2 v_2$.

In [6]:
print('matriz * eigenvector:')
print(A@evector[:,0])
print('eigenvalor * eigenvector:')
print(evalue[0]*evector[:,0])

matriz * eigenvector:
[0.89442719 0.4472136 ]
eigenvalor * eigenvector:
[0.89442719 0.4472136 ]


In [7]:
print('matriz * eigenvector:')
print(A@evector[:,1])
print('eigenvalor * eigenvector:')
print(evalue[1]*evector[:,1])

matriz * eigenvector:
[-1.66410059 -1.10940039]
eigenvalor * eigenvector:
[-1.66410059 -1.10940039]


### Ejemplo 

Si $v$ es un eigenvector entonces $cv$ es eigenvector donde: $c$ es una constante distinta de cero.


In [8]:
const = -2
const_evector = const*evector[:,0]
print(const_evector)

[-1.78885438 -0.89442719]


In [9]:
print('matriz * (constante * eigenvector):')
print(A@const_evector)
print('eigenvalor * (constante * eigenvector):')
print(evalue[0]*const_evector)

matriz * (constante * eigenvector):
[-1.78885438 -0.89442719]
eigenvalor * (constante * eigenvector):
[-1.78885438 -0.89442719]


### Ejemplo 

Una matriz con entradas reales puede tener eigenvalores y eigenvectores complejos:

In [10]:
A=np.array([[3,-5],[1,-1]])

In [11]:
print(A)

[[ 3 -5]
 [ 1 -1]]


In [12]:
evalue, evector = np.linalg.eig(A)

In [13]:
print('eigenvalores:')
print(evalue)
print('eigenvectores:')
print(evector)

eigenvalores:
[1.+1.j 1.-1.j]
eigenvectores:
[[0.91287093+0.j         0.91287093-0.j        ]
 [0.36514837-0.18257419j 0.36514837+0.18257419j]]


## Ejemplo

Los eigenvalores de una matriz diagonal son iguales a su diagonal y sus eigenvectores son los vectores canónicos $e_1, e_2, \dots e_n$.

In [17]:
A = np.diag(np.arange(1.0, 5.0, 1))

In [18]:
print(A)

[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]


In [19]:
evalue, evector = np.linalg.eig(A)

In [20]:
print('eigenvalores:')
print(evalue)
print('eigenvectores:')
print(evector)

eigenvalores:
[1. 2. 3. 4.]
eigenvectores:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Ejemplo

Los eigenvalores de una matriz triangular son iguales a su diagonal.

In [22]:
A=np.array([[10,-18, -1],
            [6,-11, 10],
            [3, 4, 8.0]])

In [23]:
A

array([[ 10., -18.,  -1.],
       [  6., -11.,  10.],
       [  3.,   4.,   8.]])

In [24]:
A = np.triu(A)

In [25]:
A

array([[ 10., -18.,  -1.],
       [  0., -11.,  10.],
       [  0.,   0.,   8.]])

In [26]:
evalue, evector = np.linalg.eig(A)

In [27]:
print('eigenvalores:')
print(evalue)
print('eigenvectores:')
print(evector)

eigenvalores:
[ 10. -11.   8.]
eigenvectores:
[[1.         0.65079137 0.97750054]
 [0.         0.7592566  0.09824126]
 [0.         0.         0.18665839]]


Ver [numpy.linalg.eig](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.eig.html).

```{admonition} Definición

Si $(\lambda, v)$ es una pareja de eigenvalor-eigenvector de $A$ tales que $Av = \lambda v$, $v$ se le nombra eigenvector derecho. Si $(\lambda, v)$ es una pareja de eigenvalor-eigenvector de $A^T$ tales que $A^Tv = \lambda v$ (que es equivalente a $v^TA=\lambda v^T$), $v$ se le nombra eigenvector izquierdo.
```

## $A$ diagonalizable

```{admonition} Definición

Si $A$ tiene $n$ eigenvectores linealmente independientes entonces $A$ se nombra diagonalizable o *non defective*. En este caso si $x_1, x_2, \dots, x_n$ son eigenvectores de $A$ con $Ax_i = \lambda_i x_i$ para $i=1,\dots,n$ entonces la igualdad anterior se escribe en ecuación matricial como:

$$AX = X \Lambda$$

o bien:

$$A = X \Lambda X^{-1}$$

donde: $X$ tiene por columnas los eigenvectores de $A$ y $\Lambda$ tiene en su diagonal los eigenvalores de $A$.

A la descomposición anterior $A = X \Lambda X^{-1}$ para $A$ diagonalizable o *non defective* se le nombra ***eigen decomposition***.
```

```{admonition} Observación
:class: tip

Si $A$ es diagonalizable o *non defective* entonces $X^{-1}A = \Lambda X^{-1}$ y los renglones de $X^{-1}$ (o equivalentemente las columnas de $X^{-T}$) son eigenvectores izquierdos.

```

```{admonition} Observación
:class: tip

Si una matriz $A$ tiene eigenvalores distintos entonces es diagonalizable.

```

## $A$ similar

```{admonition} Definición

Si existe $X \in \mathbb{R}^{n \times n}$ tal que $B = XAX^{-1}$ con $A, B \in \mathbb{R}^{n \times n}$ entonces $A$ y $B$ se nombran similares.

```

```{admonition} Observación
:class: tip

Las matrices que son similares tienen el mismo espectro, de hecho: $Ax = \lambda x$ si y sólo si $By = \lambda y$ para $y=Xx$.

```

### Resultado: $A$ simétrica

Si A es simétrica entonces tiene eigenvalores reales. Aún más: $A$ tiene eigenvectores reales linealmente independientes y forman un conjunto ortonormal, entonces $A$ se escribe como un producto de tres matrices nombrado descomposición espectral: 

$$A = Q \Lambda Q^T$$ 

donde: $Q$ es una matriz ortogonal cuyas columnas son eigenvectores de $A$ y $\Lambda$ es una matriz diagonal con eigenvalores de $A$.


```{admonition} Observaciones
:class: tip

* Los eigenvalores de $A$ simétrica se pueden ordenar:

$$\lambda_n(A) \leq \lambda_{n-1}(A) \leq \dots \leq \lambda_1(A)$$

con:

$\lambda_{max}(A) = \lambda_1(A)$, $\lambda_{min}(A) = \lambda_n(A)$.

* Se prueba para $A$ simétrica:

$$\lambda_{max}(A) = \displaystyle \max_{x \neq 0} \frac{x^TAx}{x^Tx}$$

$$\lambda_{min}(A) = \displaystyle \min_{x \neq 0} \frac{x^TAx}{x^Tx}.$$

por lo tanto:

$$\lambda_{min}(A) \leq \frac{x^TAx}{x^Tx} \leq \lambda_{max}(A) \forall x \neq 0.$$

* $||A||_2 = \displaystyle \max_{i=1,\dots,n}\{|\lambda_i|\}, ||A||_F = \left( \displaystyle \sum_{i=1}^n \lambda_i ^2 \right)^{1/2}$.
```

### Ejemplo

Matriz simétrica y descomposición espectral de la misma:

In [14]:
A=np.array([[5,4,2],[4,5,2],[2,2,2]])

In [15]:
pprint.pprint(A)

array([[5, 4, 2],
       [4, 5, 2],
       [2, 2, 2]])


In [16]:
evalue, evector = np.linalg.eigh(A)

In [17]:
print('eigenvalores:')
pprint.pprint(evalue)
print('eigenvectores:')
pprint.pprint(evector)

eigenvalores:
array([ 1.,  1., 10.])
eigenvectores:
array([[ 0.4817794 ,  0.56872152,  0.66666667],
       [-0.72665643, -0.16590957,  0.66666667],
       [ 0.48975406, -0.80562389,  0.33333333]])


In [18]:
print('descomposición espectral:')
Lambda = np.diag(evalue)
Q = evector
print('QLambdaQ^T:')
pprint.pprint(Q@Lambda@Q.T)
print('A:')
pprint.pprint(A)

descomposición espectral:
QLambdaQ^T:
array([[5., 4., 2.],
       [4., 5., 2.],
       [2., 2., 2.]])
A:
array([[5, 4, 2],
       [4, 5, 2],
       [2, 2, 2]])


Ver [numpy.linalg.eigh](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.linalg.eigh.html).

## Métodos para calcular eigenvalores y eigenvectores

Los eigenvalores de $A \in \mathbb{R}^{n \times n}$ son las raíces o ceros del **polinomio característico** definido por:

$$p(z) = \det(A-zI_n) = (-1)^nz^n + a_{n-1}z^{n-1}+ \dots + a_1z + a_0.$$