In [ ]:
#From https://documen.tician.de/pycuda/tutorial.html
#4th example: https://documen.tician.de/pycuda/array.html#pycuda.gpuarray.GPUArray

In [1]:
import pycuda.gpuarray as gpuarray
import pycuda.autoinit

import numpy

In [2]:
numpy.random.seed(0)

In [3]:
a = numpy.random.randn(4,4)

In [4]:
a.dtype

dtype('float64')

In [5]:
print(a)

[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]
 [ 0.76103773  0.12167502  0.44386323  0.33367433]]


In [6]:
a.nbytes

128

In [7]:
a_gpu = gpuarray.to_gpu(a)
a_doubled = (2*a_gpu).get()

In [8]:
a_gpu.dtype

dtype('float64')

In [9]:
print(a_gpu)

[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]
 [ 0.76103773  0.12167502  0.44386323  0.33367433]]


In [10]:
a_doubled.dtype

dtype('float64')

In [11]:
print(a_doubled)

[[ 3.52810469  0.80031442  1.95747597  4.4817864 ]
 [ 3.73511598 -1.95455576  1.90017684 -0.30271442]
 [-0.2064377   0.821197    0.28808714  2.90854701]
 [ 1.52207545  0.24335003  0.88772647  0.66734865]]
