In [1]:
import pycuda.autoinit
import pycuda.gpuarray as gpuarray
import numpy as np
import skcuda.linalg as culinalg

/home/ubuntu/.virtualenvs/pycuda_ve/lib/python3.6/site-packages/skcuda/cublas.py:283: UserWarning: creating CUBLAS context to get version number
  warnings.warn('creating CUBLAS context to get version number')


In [2]:
culinalg.init()

In [3]:
np.random.seed(0)

In [4]:
datatype = np.float64

In [5]:
m=50
n=50

In [6]:
a = np.asarray(np.random.rand(m,n), datatype)

In [7]:
print(a)

[[0.5488135  0.71518937 0.60276338 ... 0.1289263  0.31542835 0.36371077]
 [0.57019677 0.43860151 0.98837384 ... 0.02010755 0.82894003 0.00469548]
 [0.67781654 0.27000797 0.73519402 ... 0.91948261 0.7142413  0.99884701]
 ...
 [0.0698143  0.22649128 0.48110196 ... 0.43584121 0.73859222 0.52658426]
 [0.88668322 0.8309088  0.03160544 ... 0.55957053 0.5846446  0.09127072]
 [0.60047104 0.38152221 0.86758085 ... 0.72433098 0.19157101 0.66217423]]


In [8]:
a_gpu = gpuarray.to_gpu(a)

In [9]:
u_gpu, s_gpu, v_gpu = culinalg.svd(a_gpu)

In [10]:
a_rec = np.dot(u_gpu.get(), np.dot(np.diag(s_gpu.get()), v_gpu.get()))

In [11]:
#Error relativo:
np.max(np.abs(a - a_rec)/np.abs(a))

1.915426312164951e-11