# SVD

SVD para validar resultados con CUDA Toolkit E.1.

Equipo_6 

Integrantes:

* Ricardo Lastra

* Adrián Vázquez

In [5]:
import numpy as np

In [6]:
mat = np.array([[1,2,1], [4,5,3], [2,1,4]])
print(mat)

[[1 2 1]
 [4 5 3]
 [2 1 4]]


In [7]:
[U, Sigma, Vt] = np.linalg.svd(mat) # En realidad no necesitamos los brackets, se puede "U, Sigma, Vt = numpy.linalg.svd(mat)"

In [8]:
print("U:")
print(U)
print("Sigma:")
print(Sigma)
print("Vt:")
print(Vt)

U:
[[-0.28138021  0.21481929  0.93524213]
 [-0.83493576  0.42557458 -0.34895351]
 [-0.47297723 -0.87905571  0.05961205]]
Sigma:
[ 8.36009713  2.63473436  0.40859623]
Vt:
[[-0.54629481 -0.62324831 -0.55957441]
 [ 0.06034999  0.63704934 -0.7684569 ]
 [-0.83541598  0.45357433  0.31040372]]


El problema con lo anterior es que $\Sigma$ no está en forma de matriz, por lo que podemos cambiar una instrucción en la función de la siguiente manera:

In [9]:
S = np.zeros(mat.shape, "float")
S[:min(mat.shape), :min(mat.shape)] = np.diag(Sigma)
print(S)

[[ 8.36009713  0.          0.        ]
 [ 0.          2.63473436  0.        ]
 [ 0.          0.          0.40859623]]


In [10]:
np.dot(U, numpy.dot(S, Vt)) #se usa Vt

array([[ 1.,  2.,  1.],
       [ 4.,  5.,  3.],
       [ 2.,  1.,  4.]])

In [11]:
mat

array([[1, 2, 1],
       [4, 5, 3],
       [2, 1, 4]])